/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "InternalHelper_u32.h"
#include "unity.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_InternalHelper_u32__x_is_zero_y_is_zero(void);
extern void test_InternalHelper_u32__x_nonzero_y_is_zero(void);
extern void test_InternalHelper_u32__x_is_zero_y_is_one(void);
extern void test_InternalHelper_u32__x_nonzero_y_is_one(void);
extern void test_InternalHelper_u32__x_is_zero_y_is_two(void);
extern void test_InternalHelper_u32__x_is_zero_y_is_five(void);
extern void test_InternalHelper_u32__x_nonzero_y_is_five(void);
extern void test_InternalHelper_u32__x_is_250_y_is_ten(void);
extern void test_InternalHelper_u32__x_max_u32_y_is_one(void);
extern void test_InternalHelper_u32__x_is_zero_y_max_u16(void);
extern void test_InternalHelper_u32__x_at_documented_max_y_moderate(void);
extern void test_InternalHelper_u32__does_not_modify_global_counter(void);
extern void test_InternalHelper_u32__does_not_modify_global_record(void);
extern void test_InternalHelper_u32__does_not_modify_system_ready_flag(void);
extern void test_InternalHelper_u32__loop_executes_exactly_y_times(void);
extern void test_InternalHelper_u32__loop_counter_increments_correctly(void);
extern void test_InternalHelper_u32__uint16_to_uint32_cast_correctness(void);
extern void test_InternalHelper_u32__accumulation_prevents_intermediate_overflow(void);
extern void test_InternalHelper_u32__alternating_values_consistency(void);
extern void test_InternalHelper_u32__repeated_same_input_returns_same_output(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_InternalHelper_u32.c");
  run_test(test_InternalHelper_u32__x_is_zero_y_is_zero, "test_InternalHelper_u32__x_is_zero_y_is_zero", 53);
  run_test(test_InternalHelper_u32__x_nonzero_y_is_zero, "test_InternalHelper_u32__x_nonzero_y_is_zero", 76);
  run_test(test_InternalHelper_u32__x_is_zero_y_is_one, "test_InternalHelper_u32__x_is_zero_y_is_one", 101);
  run_test(test_InternalHelper_u32__x_nonzero_y_is_one, "test_InternalHelper_u32__x_nonzero_y_is_one", 125);
  run_test(test_InternalHelper_u32__x_is_zero_y_is_two, "test_InternalHelper_u32__x_is_zero_y_is_two", 156);
  run_test(test_InternalHelper_u32__x_is_zero_y_is_five, "test_InternalHelper_u32__x_is_zero_y_is_five", 186);
  run_test(test_InternalHelper_u32__x_nonzero_y_is_five, "test_InternalHelper_u32__x_nonzero_y_is_five", 211);
  run_test(test_InternalHelper_u32__x_is_250_y_is_ten, "test_InternalHelper_u32__x_is_250_y_is_ten", 236);
  run_test(test_InternalHelper_u32__x_max_u32_y_is_one, "test_InternalHelper_u32__x_max_u32_y_is_one", 263);
  run_test(test_InternalHelper_u32__x_is_zero_y_max_u16, "test_InternalHelper_u32__x_is_zero_y_max_u16", 289);
  run_test(test_InternalHelper_u32__x_at_documented_max_y_moderate, "test_InternalHelper_u32__x_at_documented_max_y_moderate", 321);
  run_test(test_InternalHelper_u32__does_not_modify_global_counter, "test_InternalHelper_u32__does_not_modify_global_counter", 349);
  run_test(test_InternalHelper_u32__does_not_modify_global_record, "test_InternalHelper_u32__does_not_modify_global_record", 373);
  run_test(test_InternalHelper_u32__does_not_modify_system_ready_flag, "test_InternalHelper_u32__does_not_modify_system_ready_flag", 399);
  run_test(test_InternalHelper_u32__loop_executes_exactly_y_times, "test_InternalHelper_u32__loop_executes_exactly_y_times", 434);
  run_test(test_InternalHelper_u32__loop_counter_increments_correctly, "test_InternalHelper_u32__loop_counter_increments_correctly", 464);
  run_test(test_InternalHelper_u32__uint16_to_uint32_cast_correctness, "test_InternalHelper_u32__uint16_to_uint32_cast_correctness", 495);
  run_test(test_InternalHelper_u32__accumulation_prevents_intermediate_overflow, "test_InternalHelper_u32__accumulation_prevents_intermediate_overflow", 521);
  run_test(test_InternalHelper_u32__alternating_values_consistency, "test_InternalHelper_u32__alternating_values_consistency", 550);
  run_test(test_InternalHelper_u32__repeated_same_input_returns_same_output, "test_InternalHelper_u32__repeated_same_input_returns_same_output", 576);

  return UNITY_END();
}
