/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include "MyLib_UpdateGlobalRecord.h"
#include "unity.h"
#include "mock_MyLib.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_MyLib_UpdateGlobalRecord_ValidInput_UpdatesDestinationAndGlobals(void);
extern void test_MyLib_UpdateGlobalRecord_NullDestinationPointer_NoUpdate(void);
extern void test_MyLib_UpdateGlobalRecord_NullSourcePointer_NoUpdate(void);
extern void test_MyLib_UpdateGlobalRecord_BothPointersNull_NoUpdate(void);
extern void test_MyLib_UpdateGlobalRecord_MultipleCallsWithDifferentValues_UpdatesCorrectly(void);
extern void test_MyLib_UpdateGlobalRecord_EdgeCaseZeroValues_UpdatesCorrectly(void);
extern void test_MyLib_UpdateGlobalRecord_EdgeCaseMaxValues_UpdatesCorrectly(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
  mock_MyLib_Init();
}
static void CMock_Verify(void)
{
  mock_MyLib_Verify();
}
static void CMock_Destroy(void)
{
  mock_MyLib_Destroy();
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_MyLib_UpdateGlobalRecord.c");
  run_test(test_MyLib_UpdateGlobalRecord_ValidInput_UpdatesDestinationAndGlobals, "test_MyLib_UpdateGlobalRecord_ValidInput_UpdatesDestinationAndGlobals", 35);
  run_test(test_MyLib_UpdateGlobalRecord_NullDestinationPointer_NoUpdate, "test_MyLib_UpdateGlobalRecord_NullDestinationPointer_NoUpdate", 71);
  run_test(test_MyLib_UpdateGlobalRecord_NullSourcePointer_NoUpdate, "test_MyLib_UpdateGlobalRecord_NullSourcePointer_NoUpdate", 99);
  run_test(test_MyLib_UpdateGlobalRecord_BothPointersNull_NoUpdate, "test_MyLib_UpdateGlobalRecord_BothPointersNull_NoUpdate", 130);
  run_test(test_MyLib_UpdateGlobalRecord_MultipleCallsWithDifferentValues_UpdatesCorrectly, "test_MyLib_UpdateGlobalRecord_MultipleCallsWithDifferentValues_UpdatesCorrectly", 160);
  run_test(test_MyLib_UpdateGlobalRecord_EdgeCaseZeroValues_UpdatesCorrectly, "test_MyLib_UpdateGlobalRecord_EdgeCaseZeroValues_UpdatesCorrectly", 197);
  run_test(test_MyLib_UpdateGlobalRecord_EdgeCaseMaxValues_UpdatesCorrectly, "test_MyLib_UpdateGlobalRecord_EdgeCaseMaxValues_UpdatesCorrectly", 227);

  CMock_Guts_MemFreeFinal();
  return UNITY_END();
}
