/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_MYLIB_H
#define _MOCK_MYLIB_H

#include "unity.h"
#include "MyLib.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_MyLib_Init(void);
void mock_MyLib_Destroy(void);
void mock_MyLib_Verify(void);




#define MyLib_ComputeAdjustedValue_u32_Ignore() TEST_FAIL_MESSAGE("MyLib_ComputeAdjustedValue_u32 requires _IgnoreAndReturn");
#define MyLib_ComputeAdjustedValue_u32_IgnoreAndReturn(cmock_retval) MyLib_ComputeAdjustedValue_u32_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void MyLib_ComputeAdjustedValue_u32_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define MyLib_ComputeAdjustedValue_u32_StopIgnore() MyLib_ComputeAdjustedValue_u32_CMockStopIgnore()
void MyLib_ComputeAdjustedValue_u32_CMockStopIgnore(void);
#define MyLib_ComputeAdjustedValue_u32_ExpectAnyArgs() TEST_FAIL_MESSAGE("MyLib_ComputeAdjustedValue_u32 requires _ExpectAnyArgsAndReturn");
#define MyLib_ComputeAdjustedValue_u32_ExpectAnyArgsAndReturn(cmock_retval) MyLib_ComputeAdjustedValue_u32_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void MyLib_ComputeAdjustedValue_u32_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define MyLib_ComputeAdjustedValue_u32_Expect(base_u32, delta_pc_u16) TEST_FAIL_MESSAGE("MyLib_ComputeAdjustedValue_u32 requires _ExpectAndReturn");
#define MyLib_ComputeAdjustedValue_u32_ExpectAndReturn(base_u32, delta_pc_u16, cmock_retval) MyLib_ComputeAdjustedValue_u32_CMockExpectAndReturn(__LINE__, base_u32, delta_pc_u16, cmock_retval)
void MyLib_ComputeAdjustedValue_u32_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t base_u32, const uint16_t* delta_pc_u16, uint32_t cmock_to_return);
typedef uint32_t (* CMOCK_MyLib_ComputeAdjustedValue_u32_CALLBACK)(uint32_t base_u32, const uint16_t* delta_pc_u16, int cmock_num_calls);
void MyLib_ComputeAdjustedValue_u32_AddCallback(CMOCK_MyLib_ComputeAdjustedValue_u32_CALLBACK Callback);
void MyLib_ComputeAdjustedValue_u32_Stub(CMOCK_MyLib_ComputeAdjustedValue_u32_CALLBACK Callback);
#define MyLib_ComputeAdjustedValue_u32_StubWithCallback MyLib_ComputeAdjustedValue_u32_Stub
#define MyLib_ComputeAdjustedValue_u32_ExpectWithArray(base_u32, delta_pc_u16, delta_pc_u16_Depth) TEST_FAIL_MESSAGE("MyLib_ComputeAdjustedValue_u32 requires _ExpectWithArrayAndReturn");
#define MyLib_ComputeAdjustedValue_u32_ExpectWithArrayAndReturn(base_u32, delta_pc_u16, delta_pc_u16_Depth, cmock_retval) MyLib_ComputeAdjustedValue_u32_CMockExpectWithArrayAndReturn(__LINE__, base_u32, delta_pc_u16, (delta_pc_u16_Depth), cmock_retval)
void MyLib_ComputeAdjustedValue_u32_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t base_u32, const uint16_t* delta_pc_u16, int delta_pc_u16_Depth, uint32_t cmock_to_return);
#define MyLib_ComputeAdjustedValue_u32_IgnoreArg_base_u32() MyLib_ComputeAdjustedValue_u32_CMockIgnoreArg_base_u32(__LINE__)
void MyLib_ComputeAdjustedValue_u32_CMockIgnoreArg_base_u32(UNITY_LINE_TYPE cmock_line);
#define MyLib_ComputeAdjustedValue_u32_IgnoreArg_delta_pc_u16() MyLib_ComputeAdjustedValue_u32_CMockIgnoreArg_delta_pc_u16(__LINE__)
void MyLib_ComputeAdjustedValue_u32_CMockIgnoreArg_delta_pc_u16(UNITY_LINE_TYPE cmock_line);
#define MyLib_AnalyzeArray_u32_Ignore() TEST_FAIL_MESSAGE("MyLib_AnalyzeArray_u32 requires _IgnoreAndReturn");
#define MyLib_AnalyzeArray_u32_IgnoreAndReturn(cmock_retval) MyLib_AnalyzeArray_u32_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void MyLib_AnalyzeArray_u32_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define MyLib_AnalyzeArray_u32_StopIgnore() MyLib_AnalyzeArray_u32_CMockStopIgnore()
void MyLib_AnalyzeArray_u32_CMockStopIgnore(void);
#define MyLib_AnalyzeArray_u32_ExpectAnyArgs() TEST_FAIL_MESSAGE("MyLib_AnalyzeArray_u32 requires _ExpectAnyArgsAndReturn");
#define MyLib_AnalyzeArray_u32_ExpectAnyArgsAndReturn(cmock_retval) MyLib_AnalyzeArray_u32_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void MyLib_AnalyzeArray_u32_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define MyLib_AnalyzeArray_u32_Expect(values_pu16, len_u32, factor_u16) TEST_FAIL_MESSAGE("MyLib_AnalyzeArray_u32 requires _ExpectAndReturn");
#define MyLib_AnalyzeArray_u32_ExpectAndReturn(values_pu16, len_u32, factor_u16, cmock_retval) MyLib_AnalyzeArray_u32_CMockExpectAndReturn(__LINE__, values_pu16, len_u32, factor_u16, cmock_retval)
void MyLib_AnalyzeArray_u32_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t* values_pu16, size_t len_u32, uint16_t factor_u16, uint32_t cmock_to_return);
typedef uint32_t (* CMOCK_MyLib_AnalyzeArray_u32_CALLBACK)(uint16_t* values_pu16, size_t len_u32, uint16_t factor_u16, int cmock_num_calls);
void MyLib_AnalyzeArray_u32_AddCallback(CMOCK_MyLib_AnalyzeArray_u32_CALLBACK Callback);
void MyLib_AnalyzeArray_u32_Stub(CMOCK_MyLib_AnalyzeArray_u32_CALLBACK Callback);
#define MyLib_AnalyzeArray_u32_StubWithCallback MyLib_AnalyzeArray_u32_Stub
#define MyLib_AnalyzeArray_u32_ExpectWithArray(values_pu16, values_pu16_Depth, len_u32, factor_u16) TEST_FAIL_MESSAGE("MyLib_AnalyzeArray_u32 requires _ExpectWithArrayAndReturn");
#define MyLib_AnalyzeArray_u32_ExpectWithArrayAndReturn(values_pu16, values_pu16_Depth, len_u32, factor_u16, cmock_retval) MyLib_AnalyzeArray_u32_CMockExpectWithArrayAndReturn(__LINE__, values_pu16, (values_pu16_Depth), len_u32, factor_u16, cmock_retval)
void MyLib_AnalyzeArray_u32_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t* values_pu16, int values_pu16_Depth, size_t len_u32, uint16_t factor_u16, uint32_t cmock_to_return);
#define MyLib_AnalyzeArray_u32_ReturnThruPtr_values_pu16(values_pu16) MyLib_AnalyzeArray_u32_CMockReturnMemThruPtr_values_pu16(__LINE__, values_pu16, sizeof(uint16_t))
#define MyLib_AnalyzeArray_u32_ReturnArrayThruPtr_values_pu16(values_pu16, cmock_len) MyLib_AnalyzeArray_u32_CMockReturnMemThruPtr_values_pu16(__LINE__, values_pu16, (cmock_len * sizeof(*values_pu16)))
#define MyLib_AnalyzeArray_u32_ReturnMemThruPtr_values_pu16(values_pu16, cmock_size) MyLib_AnalyzeArray_u32_CMockReturnMemThruPtr_values_pu16(__LINE__, values_pu16, (cmock_size))
void MyLib_AnalyzeArray_u32_CMockReturnMemThruPtr_values_pu16(UNITY_LINE_TYPE cmock_line, uint16_t const* values_pu16, size_t cmock_size);
#define MyLib_AnalyzeArray_u32_IgnoreArg_values_pu16() MyLib_AnalyzeArray_u32_CMockIgnoreArg_values_pu16(__LINE__)
void MyLib_AnalyzeArray_u32_CMockIgnoreArg_values_pu16(UNITY_LINE_TYPE cmock_line);
#define MyLib_AnalyzeArray_u32_IgnoreArg_len_u32() MyLib_AnalyzeArray_u32_CMockIgnoreArg_len_u32(__LINE__)
void MyLib_AnalyzeArray_u32_CMockIgnoreArg_len_u32(UNITY_LINE_TYPE cmock_line);
#define MyLib_AnalyzeArray_u32_IgnoreArg_factor_u16() MyLib_AnalyzeArray_u32_CMockIgnoreArg_factor_u16(__LINE__)
void MyLib_AnalyzeArray_u32_CMockIgnoreArg_factor_u16(UNITY_LINE_TYPE cmock_line);
#define MyLib_UpdateGlobalRecord_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("MyLib_UpdateGlobalRecord requires _Ignore (not AndReturn)");
#define MyLib_UpdateGlobalRecord_Ignore() MyLib_UpdateGlobalRecord_CMockIgnore()
void MyLib_UpdateGlobalRecord_CMockIgnore(void);
#define MyLib_UpdateGlobalRecord_StopIgnore() MyLib_UpdateGlobalRecord_CMockStopIgnore()
void MyLib_UpdateGlobalRecord_CMockStopIgnore(void);
#define MyLib_UpdateGlobalRecord_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("MyLib_UpdateGlobalRecord requires _ExpectAnyArgs (not AndReturn)");
#define MyLib_UpdateGlobalRecord_ExpectAnyArgs() MyLib_UpdateGlobalRecord_CMockExpectAnyArgs(__LINE__)
void MyLib_UpdateGlobalRecord_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define MyLib_UpdateGlobalRecord_ExpectAndReturn(dest_p, src_pc, cmock_retval) TEST_FAIL_MESSAGE("MyLib_UpdateGlobalRecord requires _Expect (not AndReturn)");
#define MyLib_UpdateGlobalRecord_Expect(dest_p, src_pc) MyLib_UpdateGlobalRecord_CMockExpect(__LINE__, dest_p, src_pc)
void MyLib_UpdateGlobalRecord_CMockExpect(UNITY_LINE_TYPE cmock_line, MyLib_record_t* dest_p, const MyLib_record_t* src_pc);
typedef void (* CMOCK_MyLib_UpdateGlobalRecord_CALLBACK)(MyLib_record_t* dest_p, const MyLib_record_t* src_pc, int cmock_num_calls);
void MyLib_UpdateGlobalRecord_AddCallback(CMOCK_MyLib_UpdateGlobalRecord_CALLBACK Callback);
void MyLib_UpdateGlobalRecord_Stub(CMOCK_MyLib_UpdateGlobalRecord_CALLBACK Callback);
#define MyLib_UpdateGlobalRecord_StubWithCallback MyLib_UpdateGlobalRecord_Stub
#define MyLib_UpdateGlobalRecord_ExpectWithArrayAndReturn(dest_p, dest_p_Depth, src_pc, src_pc_Depth, cmock_retval) TEST_FAIL_MESSAGE("MyLib_UpdateGlobalRecord requires _ExpectWithArray (not AndReturn)");
#define MyLib_UpdateGlobalRecord_ExpectWithArray(dest_p, dest_p_Depth, src_pc, src_pc_Depth) MyLib_UpdateGlobalRecord_CMockExpectWithArray(__LINE__, dest_p, (dest_p_Depth), src_pc, (src_pc_Depth))
void MyLib_UpdateGlobalRecord_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, MyLib_record_t* dest_p, int dest_p_Depth, const MyLib_record_t* src_pc, int src_pc_Depth);
#define MyLib_UpdateGlobalRecord_ReturnThruPtr_dest_p(dest_p) MyLib_UpdateGlobalRecord_CMockReturnMemThruPtr_dest_p(__LINE__, dest_p, sizeof(MyLib_record_t))
#define MyLib_UpdateGlobalRecord_ReturnArrayThruPtr_dest_p(dest_p, cmock_len) MyLib_UpdateGlobalRecord_CMockReturnMemThruPtr_dest_p(__LINE__, dest_p, (cmock_len * sizeof(*dest_p)))
#define MyLib_UpdateGlobalRecord_ReturnMemThruPtr_dest_p(dest_p, cmock_size) MyLib_UpdateGlobalRecord_CMockReturnMemThruPtr_dest_p(__LINE__, dest_p, (cmock_size))
void MyLib_UpdateGlobalRecord_CMockReturnMemThruPtr_dest_p(UNITY_LINE_TYPE cmock_line, MyLib_record_t const* dest_p, size_t cmock_size);
#define MyLib_UpdateGlobalRecord_IgnoreArg_dest_p() MyLib_UpdateGlobalRecord_CMockIgnoreArg_dest_p(__LINE__)
void MyLib_UpdateGlobalRecord_CMockIgnoreArg_dest_p(UNITY_LINE_TYPE cmock_line);
#define MyLib_UpdateGlobalRecord_IgnoreArg_src_pc() MyLib_UpdateGlobalRecord_CMockIgnoreArg_src_pc(__LINE__)
void MyLib_UpdateGlobalRecord_CMockIgnoreArg_src_pc(UNITY_LINE_TYPE cmock_line);
#define MyLib_Orchestrate_u32_Ignore() TEST_FAIL_MESSAGE("MyLib_Orchestrate_u32 requires _IgnoreAndReturn");
#define MyLib_Orchestrate_u32_IgnoreAndReturn(cmock_retval) MyLib_Orchestrate_u32_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void MyLib_Orchestrate_u32_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define MyLib_Orchestrate_u32_StopIgnore() MyLib_Orchestrate_u32_CMockStopIgnore()
void MyLib_Orchestrate_u32_CMockStopIgnore(void);
#define MyLib_Orchestrate_u32_ExpectAnyArgs() TEST_FAIL_MESSAGE("MyLib_Orchestrate_u32 requires _ExpectAnyArgsAndReturn");
#define MyLib_Orchestrate_u32_ExpectAnyArgsAndReturn(cmock_retval) MyLib_Orchestrate_u32_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void MyLib_Orchestrate_u32_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define MyLib_Orchestrate_u32_Expect(start_u32, delta_pc_u16) TEST_FAIL_MESSAGE("MyLib_Orchestrate_u32 requires _ExpectAndReturn");
#define MyLib_Orchestrate_u32_ExpectAndReturn(start_u32, delta_pc_u16, cmock_retval) MyLib_Orchestrate_u32_CMockExpectAndReturn(__LINE__, start_u32, delta_pc_u16, cmock_retval)
void MyLib_Orchestrate_u32_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t start_u32, const uint16_t* delta_pc_u16, uint32_t cmock_to_return);
typedef uint32_t (* CMOCK_MyLib_Orchestrate_u32_CALLBACK)(uint32_t start_u32, const uint16_t* delta_pc_u16, int cmock_num_calls);
void MyLib_Orchestrate_u32_AddCallback(CMOCK_MyLib_Orchestrate_u32_CALLBACK Callback);
void MyLib_Orchestrate_u32_Stub(CMOCK_MyLib_Orchestrate_u32_CALLBACK Callback);
#define MyLib_Orchestrate_u32_StubWithCallback MyLib_Orchestrate_u32_Stub
#define MyLib_Orchestrate_u32_ExpectWithArray(start_u32, delta_pc_u16, delta_pc_u16_Depth) TEST_FAIL_MESSAGE("MyLib_Orchestrate_u32 requires _ExpectWithArrayAndReturn");
#define MyLib_Orchestrate_u32_ExpectWithArrayAndReturn(start_u32, delta_pc_u16, delta_pc_u16_Depth, cmock_retval) MyLib_Orchestrate_u32_CMockExpectWithArrayAndReturn(__LINE__, start_u32, delta_pc_u16, (delta_pc_u16_Depth), cmock_retval)
void MyLib_Orchestrate_u32_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t start_u32, const uint16_t* delta_pc_u16, int delta_pc_u16_Depth, uint32_t cmock_to_return);
#define MyLib_Orchestrate_u32_IgnoreArg_start_u32() MyLib_Orchestrate_u32_CMockIgnoreArg_start_u32(__LINE__)
void MyLib_Orchestrate_u32_CMockIgnoreArg_start_u32(UNITY_LINE_TYPE cmock_line);
#define MyLib_Orchestrate_u32_IgnoreArg_delta_pc_u16() MyLib_Orchestrate_u32_CMockIgnoreArg_delta_pc_u16(__LINE__)
void MyLib_Orchestrate_u32_CMockIgnoreArg_delta_pc_u16(UNITY_LINE_TYPE cmock_line);
#define InternalHelper_u32_Ignore() TEST_FAIL_MESSAGE("InternalHelper_u32 requires _IgnoreAndReturn");
#define InternalHelper_u32_IgnoreAndReturn(cmock_retval) InternalHelper_u32_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void InternalHelper_u32_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define InternalHelper_u32_StopIgnore() InternalHelper_u32_CMockStopIgnore()
void InternalHelper_u32_CMockStopIgnore(void);
#define InternalHelper_u32_ExpectAnyArgs() TEST_FAIL_MESSAGE("InternalHelper_u32 requires _ExpectAnyArgsAndReturn");
#define InternalHelper_u32_ExpectAnyArgsAndReturn(cmock_retval) InternalHelper_u32_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void InternalHelper_u32_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define InternalHelper_u32_Expect(x_u32, y_u16) TEST_FAIL_MESSAGE("InternalHelper_u32 requires _ExpectAndReturn");
#define InternalHelper_u32_ExpectAndReturn(x_u32, y_u16, cmock_retval) InternalHelper_u32_CMockExpectAndReturn(__LINE__, x_u32, y_u16, cmock_retval)
void InternalHelper_u32_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t x_u32, uint16_t y_u16, uint32_t cmock_to_return);
typedef uint32_t (* CMOCK_InternalHelper_u32_CALLBACK)(uint32_t x_u32, uint16_t y_u16, int cmock_num_calls);
void InternalHelper_u32_AddCallback(CMOCK_InternalHelper_u32_CALLBACK Callback);
void InternalHelper_u32_Stub(CMOCK_InternalHelper_u32_CALLBACK Callback);
#define InternalHelper_u32_StubWithCallback InternalHelper_u32_Stub
#define InternalHelper_u32_IgnoreArg_x_u32() InternalHelper_u32_CMockIgnoreArg_x_u32(__LINE__)
void InternalHelper_u32_CMockIgnoreArg_x_u32(UNITY_LINE_TYPE cmock_line);
#define InternalHelper_u32_IgnoreArg_y_u16() InternalHelper_u32_CMockIgnoreArg_y_u16(__LINE__)
void InternalHelper_u32_CMockIgnoreArg_y_u16(UNITY_LINE_TYPE cmock_line);
#define MyLib_UpdateCounter_u8_Ignore() TEST_FAIL_MESSAGE("MyLib_UpdateCounter_u8 requires _IgnoreAndReturn");
#define MyLib_UpdateCounter_u8_IgnoreAndReturn(cmock_retval) MyLib_UpdateCounter_u8_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void MyLib_UpdateCounter_u8_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define MyLib_UpdateCounter_u8_StopIgnore() MyLib_UpdateCounter_u8_CMockStopIgnore()
void MyLib_UpdateCounter_u8_CMockStopIgnore(void);
#define MyLib_UpdateCounter_u8_ExpectAnyArgs() TEST_FAIL_MESSAGE("MyLib_UpdateCounter_u8 requires _ExpectAnyArgsAndReturn");
#define MyLib_UpdateCounter_u8_ExpectAnyArgsAndReturn(cmock_retval) MyLib_UpdateCounter_u8_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void MyLib_UpdateCounter_u8_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define MyLib_UpdateCounter_u8_Expect(add_u32) TEST_FAIL_MESSAGE("MyLib_UpdateCounter_u8 requires _ExpectAndReturn");
#define MyLib_UpdateCounter_u8_ExpectAndReturn(add_u32, cmock_retval) MyLib_UpdateCounter_u8_CMockExpectAndReturn(__LINE__, add_u32, cmock_retval)
void MyLib_UpdateCounter_u8_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t add_u32, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_MyLib_UpdateCounter_u8_CALLBACK)(uint32_t add_u32, int cmock_num_calls);
void MyLib_UpdateCounter_u8_AddCallback(CMOCK_MyLib_UpdateCounter_u8_CALLBACK Callback);
void MyLib_UpdateCounter_u8_Stub(CMOCK_MyLib_UpdateCounter_u8_CALLBACK Callback);
#define MyLib_UpdateCounter_u8_StubWithCallback MyLib_UpdateCounter_u8_Stub
#define MyLib_UpdateCounter_u8_IgnoreArg_add_u32() MyLib_UpdateCounter_u8_CMockIgnoreArg_add_u32(__LINE__)
void MyLib_UpdateCounter_u8_CMockIgnoreArg_add_u32(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
