#ifndef TEST_SYNTAX_MULTILINERETURNANDPARAMS_U32_HELP_H
#define TEST_SYNTAX_MULTILINERETURNANDPARAMS_U32_HELP_H

#include "Syntax_MultilineReturnAndParams_u32.h"
#include <stddef.h>
#include <string.h>

#endif /* TEST_SYNTAX_MULTILINERETURNANDPARAMS_U32_HELP_H */
