/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_MyLib.h"

static const char* CMockString_InternalHelper_u32 = "InternalHelper_u32";
static const char* CMockString_MyLib_AnalyzeArray_u32 = "MyLib_AnalyzeArray_u32";
static const char* CMockString_MyLib_ComputeAdjustedValue_u32 = "MyLib_ComputeAdjustedValue_u32";
static const char* CMockString_MyLib_Orchestrate_u32 = "MyLib_Orchestrate_u32";
static const char* CMockString_MyLib_ProcessRecord = "MyLib_ProcessRecord";
static const char* CMockString_MyLib_UpdateCounter_u8 = "MyLib_UpdateCounter_u8";
static const char* CMockString_MyLib_UpdateGlobalRecord = "MyLib_UpdateGlobalRecord";
static const char* CMockString_add_u32 = "add_u32";
static const char* CMockString_base_u32 = "base_u32";
static const char* CMockString_delta_pc_u16 = "delta_pc_u16";
static const char* CMockString_dest_p = "dest_p";
static const char* CMockString_factor_u16 = "factor_u16";
static const char* CMockString_len_u32 = "len_u32";
static const char* CMockString_multiplier_u8 = "multiplier_u8";
static const char* CMockString_rec_pc = "rec_pc";
static const char* CMockString_src_pc = "src_pc";
static const char* CMockString_start_u32 = "start_u32";
static const char* CMockString_values_pu16 = "values_pu16";
static const char* CMockString_x_u32 = "x_u32";
static const char* CMockString_y_u16 = "y_u16";

typedef struct _CMOCK_MyLib_ProcessRecord_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int CallOrder;
  const MyLib_record_t* Expected_rec_pc;
  uint8_t Expected_multiplier_u8;
  int Expected_rec_pc_Depth;
  char IgnoreArg_rec_pc;
  char IgnoreArg_multiplier_u8;

} CMOCK_MyLib_ProcessRecord_CALL_INSTANCE;

typedef struct _CMOCK_MyLib_ComputeAdjustedValue_u32_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint32_t ReturnVal;
  int CallOrder;
  uint32_t Expected_base_u32;
  const uint16_t* Expected_delta_pc_u16;
  int Expected_delta_pc_u16_Depth;
  char IgnoreArg_base_u32;
  char IgnoreArg_delta_pc_u16;

} CMOCK_MyLib_ComputeAdjustedValue_u32_CALL_INSTANCE;

typedef struct _CMOCK_MyLib_AnalyzeArray_u32_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint32_t ReturnVal;
  int CallOrder;
  uint16_t* Expected_values_pu16;
  size_t Expected_len_u32;
  uint16_t Expected_factor_u16;
  int Expected_values_pu16_Depth;
  char ReturnThruPtr_values_pu16_Used;
  uint16_t const* ReturnThruPtr_values_pu16_Val;
  size_t ReturnThruPtr_values_pu16_Size;
  char IgnoreArg_values_pu16;
  char IgnoreArg_len_u32;
  char IgnoreArg_factor_u16;

} CMOCK_MyLib_AnalyzeArray_u32_CALL_INSTANCE;

typedef struct _CMOCK_MyLib_UpdateGlobalRecord_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int CallOrder;
  MyLib_record_t* Expected_dest_p;
  const MyLib_record_t* Expected_src_pc;
  int Expected_dest_p_Depth;
  int Expected_src_pc_Depth;
  char ReturnThruPtr_dest_p_Used;
  MyLib_record_t const* ReturnThruPtr_dest_p_Val;
  size_t ReturnThruPtr_dest_p_Size;
  char IgnoreArg_dest_p;
  char IgnoreArg_src_pc;

} CMOCK_MyLib_UpdateGlobalRecord_CALL_INSTANCE;

typedef struct _CMOCK_MyLib_Orchestrate_u32_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint32_t ReturnVal;
  int CallOrder;
  uint32_t Expected_start_u32;
  const uint16_t* Expected_delta_pc_u16;
  int Expected_delta_pc_u16_Depth;
  char IgnoreArg_start_u32;
  char IgnoreArg_delta_pc_u16;

} CMOCK_MyLib_Orchestrate_u32_CALL_INSTANCE;

typedef struct _CMOCK_InternalHelper_u32_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint32_t ReturnVal;
  int CallOrder;
  uint32_t Expected_x_u32;
  uint16_t Expected_y_u16;
  char IgnoreArg_x_u32;
  char IgnoreArg_y_u16;

} CMOCK_InternalHelper_u32_CALL_INSTANCE;

typedef struct _CMOCK_MyLib_UpdateCounter_u8_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint8_t ReturnVal;
  int CallOrder;
  uint32_t Expected_add_u32;
  char IgnoreArg_add_u32;

} CMOCK_MyLib_UpdateCounter_u8_CALL_INSTANCE;

static struct mock_MyLibInstance
{
  char MyLib_ProcessRecord_IgnoreBool;
  char MyLib_ProcessRecord_CallbackBool;
  CMOCK_MyLib_ProcessRecord_CALLBACK MyLib_ProcessRecord_CallbackFunctionPointer;
  int MyLib_ProcessRecord_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE MyLib_ProcessRecord_CallInstance;
  char MyLib_ComputeAdjustedValue_u32_IgnoreBool;
  uint32_t MyLib_ComputeAdjustedValue_u32_FinalReturn;
  char MyLib_ComputeAdjustedValue_u32_CallbackBool;
  CMOCK_MyLib_ComputeAdjustedValue_u32_CALLBACK MyLib_ComputeAdjustedValue_u32_CallbackFunctionPointer;
  int MyLib_ComputeAdjustedValue_u32_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE MyLib_ComputeAdjustedValue_u32_CallInstance;
  char MyLib_AnalyzeArray_u32_IgnoreBool;
  uint32_t MyLib_AnalyzeArray_u32_FinalReturn;
  char MyLib_AnalyzeArray_u32_CallbackBool;
  CMOCK_MyLib_AnalyzeArray_u32_CALLBACK MyLib_AnalyzeArray_u32_CallbackFunctionPointer;
  int MyLib_AnalyzeArray_u32_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE MyLib_AnalyzeArray_u32_CallInstance;
  char MyLib_UpdateGlobalRecord_IgnoreBool;
  char MyLib_UpdateGlobalRecord_CallbackBool;
  CMOCK_MyLib_UpdateGlobalRecord_CALLBACK MyLib_UpdateGlobalRecord_CallbackFunctionPointer;
  int MyLib_UpdateGlobalRecord_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE MyLib_UpdateGlobalRecord_CallInstance;
  char MyLib_Orchestrate_u32_IgnoreBool;
  uint32_t MyLib_Orchestrate_u32_FinalReturn;
  char MyLib_Orchestrate_u32_CallbackBool;
  CMOCK_MyLib_Orchestrate_u32_CALLBACK MyLib_Orchestrate_u32_CallbackFunctionPointer;
  int MyLib_Orchestrate_u32_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE MyLib_Orchestrate_u32_CallInstance;
  char InternalHelper_u32_IgnoreBool;
  uint32_t InternalHelper_u32_FinalReturn;
  char InternalHelper_u32_CallbackBool;
  CMOCK_InternalHelper_u32_CALLBACK InternalHelper_u32_CallbackFunctionPointer;
  int InternalHelper_u32_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE InternalHelper_u32_CallInstance;
  char MyLib_UpdateCounter_u8_IgnoreBool;
  uint8_t MyLib_UpdateCounter_u8_FinalReturn;
  char MyLib_UpdateCounter_u8_CallbackBool;
  CMOCK_MyLib_UpdateCounter_u8_CALLBACK MyLib_UpdateCounter_u8_CallbackFunctionPointer;
  int MyLib_UpdateCounter_u8_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE MyLib_UpdateCounter_u8_CallInstance;
} Mock;

extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_MyLib_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.MyLib_ProcessRecord_CallInstance;
  if (Mock.MyLib_ProcessRecord_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_MyLib_ProcessRecord);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.MyLib_ProcessRecord_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.MyLib_ComputeAdjustedValue_u32_CallInstance;
  if (Mock.MyLib_ComputeAdjustedValue_u32_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_MyLib_ComputeAdjustedValue_u32);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.MyLib_ComputeAdjustedValue_u32_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.MyLib_AnalyzeArray_u32_CallInstance;
  if (Mock.MyLib_AnalyzeArray_u32_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_MyLib_AnalyzeArray_u32);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.MyLib_AnalyzeArray_u32_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.MyLib_UpdateGlobalRecord_CallInstance;
  if (Mock.MyLib_UpdateGlobalRecord_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_MyLib_UpdateGlobalRecord);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.MyLib_UpdateGlobalRecord_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.MyLib_Orchestrate_u32_CallInstance;
  if (Mock.MyLib_Orchestrate_u32_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_MyLib_Orchestrate_u32);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.MyLib_Orchestrate_u32_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.InternalHelper_u32_CallInstance;
  if (Mock.InternalHelper_u32_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_InternalHelper_u32);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.InternalHelper_u32_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.MyLib_UpdateCounter_u8_CallInstance;
  if (Mock.MyLib_UpdateCounter_u8_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_MyLib_UpdateCounter_u8);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.MyLib_UpdateCounter_u8_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_MyLib_Init(void)
{
  mock_MyLib_Destroy();
}

void mock_MyLib_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

void MyLib_ProcessRecord(const MyLib_record_t* rec_pc, uint8_t multiplier_u8)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MyLib_ProcessRecord_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_MyLib_ProcessRecord);
  cmock_call_instance = (CMOCK_MyLib_ProcessRecord_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.MyLib_ProcessRecord_CallInstance);
  Mock.MyLib_ProcessRecord_CallInstance = CMock_Guts_MemNext(Mock.MyLib_ProcessRecord_CallInstance);
  if (Mock.MyLib_ProcessRecord_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.MyLib_ProcessRecord_CallbackBool &&
      Mock.MyLib_ProcessRecord_CallbackFunctionPointer != NULL)
  {
    Mock.MyLib_ProcessRecord_CallbackFunctionPointer(rec_pc, multiplier_u8, Mock.MyLib_ProcessRecord_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_rec_pc)
  {
    UNITY_SET_DETAILS(CMockString_MyLib_ProcessRecord,CMockString_rec_pc);
    if (cmock_call_instance->Expected_rec_pc == NULL)
      { UNITY_TEST_ASSERT_NULL(rec_pc, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_rec_pc), (void*)(rec_pc), sizeof(const MyLib_record_t), cmock_call_instance->Expected_rec_pc_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_multiplier_u8)
  {
    UNITY_SET_DETAILS(CMockString_MyLib_ProcessRecord,CMockString_multiplier_u8);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_multiplier_u8, multiplier_u8, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.MyLib_ProcessRecord_CallbackFunctionPointer != NULL)
  {
    Mock.MyLib_ProcessRecord_CallbackFunctionPointer(rec_pc, multiplier_u8, Mock.MyLib_ProcessRecord_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_MyLib_ProcessRecord(CMOCK_MyLib_ProcessRecord_CALL_INSTANCE* cmock_call_instance, const MyLib_record_t* rec_pc, int rec_pc_Depth, uint8_t multiplier_u8);
void CMockExpectParameters_MyLib_ProcessRecord(CMOCK_MyLib_ProcessRecord_CALL_INSTANCE* cmock_call_instance, const MyLib_record_t* rec_pc, int rec_pc_Depth, uint8_t multiplier_u8)
{
  cmock_call_instance->Expected_rec_pc = rec_pc;
  cmock_call_instance->Expected_rec_pc_Depth = rec_pc_Depth;
  cmock_call_instance->IgnoreArg_rec_pc = 0;
  cmock_call_instance->Expected_multiplier_u8 = multiplier_u8;
  cmock_call_instance->IgnoreArg_multiplier_u8 = 0;
}

void MyLib_ProcessRecord_CMockIgnore(void)
{
  Mock.MyLib_ProcessRecord_IgnoreBool = (char)1;
}

void MyLib_ProcessRecord_CMockStopIgnore(void)
{
  Mock.MyLib_ProcessRecord_IgnoreBool = (char)0;
}

void MyLib_ProcessRecord_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MyLib_ProcessRecord_CALL_INSTANCE));
  CMOCK_MyLib_ProcessRecord_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_ProcessRecord_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MyLib_ProcessRecord_CallInstance = CMock_Guts_MemChain(Mock.MyLib_ProcessRecord_CallInstance, cmock_guts_index);
  Mock.MyLib_ProcessRecord_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void MyLib_ProcessRecord_CMockExpect(UNITY_LINE_TYPE cmock_line, const MyLib_record_t* rec_pc, uint8_t multiplier_u8)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MyLib_ProcessRecord_CALL_INSTANCE));
  CMOCK_MyLib_ProcessRecord_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_ProcessRecord_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MyLib_ProcessRecord_CallInstance = CMock_Guts_MemChain(Mock.MyLib_ProcessRecord_CallInstance, cmock_guts_index);
  Mock.MyLib_ProcessRecord_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_MyLib_ProcessRecord(cmock_call_instance, rec_pc, 1, multiplier_u8);
}

void MyLib_ProcessRecord_AddCallback(CMOCK_MyLib_ProcessRecord_CALLBACK Callback)
{
  Mock.MyLib_ProcessRecord_IgnoreBool = (char)0;
  Mock.MyLib_ProcessRecord_CallbackBool = (char)1;
  Mock.MyLib_ProcessRecord_CallbackFunctionPointer = Callback;
}

void MyLib_ProcessRecord_Stub(CMOCK_MyLib_ProcessRecord_CALLBACK Callback)
{
  Mock.MyLib_ProcessRecord_IgnoreBool = (char)0;
  Mock.MyLib_ProcessRecord_CallbackBool = (char)0;
  Mock.MyLib_ProcessRecord_CallbackFunctionPointer = Callback;
}

void MyLib_ProcessRecord_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, const MyLib_record_t* rec_pc, int rec_pc_Depth, uint8_t multiplier_u8)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MyLib_ProcessRecord_CALL_INSTANCE));
  CMOCK_MyLib_ProcessRecord_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_ProcessRecord_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MyLib_ProcessRecord_CallInstance = CMock_Guts_MemChain(Mock.MyLib_ProcessRecord_CallInstance, cmock_guts_index);
  Mock.MyLib_ProcessRecord_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_MyLib_ProcessRecord(cmock_call_instance, rec_pc, rec_pc_Depth, multiplier_u8);
}

void MyLib_ProcessRecord_CMockIgnoreArg_rec_pc(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MyLib_ProcessRecord_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_ProcessRecord_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.MyLib_ProcessRecord_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_rec_pc = 1;
}

void MyLib_ProcessRecord_CMockIgnoreArg_multiplier_u8(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MyLib_ProcessRecord_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_ProcessRecord_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.MyLib_ProcessRecord_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_multiplier_u8 = 1;
}

uint32_t MyLib_ComputeAdjustedValue_u32(uint32_t base_u32, const uint16_t* delta_pc_u16)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MyLib_ComputeAdjustedValue_u32_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_MyLib_ComputeAdjustedValue_u32);
  cmock_call_instance = (CMOCK_MyLib_ComputeAdjustedValue_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.MyLib_ComputeAdjustedValue_u32_CallInstance);
  Mock.MyLib_ComputeAdjustedValue_u32_CallInstance = CMock_Guts_MemNext(Mock.MyLib_ComputeAdjustedValue_u32_CallInstance);
  if (Mock.MyLib_ComputeAdjustedValue_u32_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.MyLib_ComputeAdjustedValue_u32_FinalReturn;
    Mock.MyLib_ComputeAdjustedValue_u32_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.MyLib_ComputeAdjustedValue_u32_CallbackBool &&
      Mock.MyLib_ComputeAdjustedValue_u32_CallbackFunctionPointer != NULL)
  {
    uint32_t cmock_cb_ret = Mock.MyLib_ComputeAdjustedValue_u32_CallbackFunctionPointer(base_u32, delta_pc_u16, Mock.MyLib_ComputeAdjustedValue_u32_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_base_u32)
  {
    UNITY_SET_DETAILS(CMockString_MyLib_ComputeAdjustedValue_u32,CMockString_base_u32);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_base_u32, base_u32, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_delta_pc_u16)
  {
    UNITY_SET_DETAILS(CMockString_MyLib_ComputeAdjustedValue_u32,CMockString_delta_pc_u16);
    if (cmock_call_instance->Expected_delta_pc_u16 == NULL)
      { UNITY_TEST_ASSERT_NULL(delta_pc_u16, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX16_ARRAY(cmock_call_instance->Expected_delta_pc_u16, delta_pc_u16, cmock_call_instance->Expected_delta_pc_u16_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.MyLib_ComputeAdjustedValue_u32_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.MyLib_ComputeAdjustedValue_u32_CallbackFunctionPointer(base_u32, delta_pc_u16, Mock.MyLib_ComputeAdjustedValue_u32_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_MyLib_ComputeAdjustedValue_u32(CMOCK_MyLib_ComputeAdjustedValue_u32_CALL_INSTANCE* cmock_call_instance, uint32_t base_u32, const uint16_t* delta_pc_u16, int delta_pc_u16_Depth);
void CMockExpectParameters_MyLib_ComputeAdjustedValue_u32(CMOCK_MyLib_ComputeAdjustedValue_u32_CALL_INSTANCE* cmock_call_instance, uint32_t base_u32, const uint16_t* delta_pc_u16, int delta_pc_u16_Depth)
{
  cmock_call_instance->Expected_base_u32 = base_u32;
  cmock_call_instance->IgnoreArg_base_u32 = 0;
  cmock_call_instance->Expected_delta_pc_u16 = delta_pc_u16;
  cmock_call_instance->Expected_delta_pc_u16_Depth = delta_pc_u16_Depth;
  cmock_call_instance->IgnoreArg_delta_pc_u16 = 0;
}

void MyLib_ComputeAdjustedValue_u32_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MyLib_ComputeAdjustedValue_u32_CALL_INSTANCE));
  CMOCK_MyLib_ComputeAdjustedValue_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_ComputeAdjustedValue_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MyLib_ComputeAdjustedValue_u32_CallInstance = CMock_Guts_MemChain(Mock.MyLib_ComputeAdjustedValue_u32_CallInstance, cmock_guts_index);
  Mock.MyLib_ComputeAdjustedValue_u32_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.MyLib_ComputeAdjustedValue_u32_IgnoreBool = (char)1;
}

void MyLib_ComputeAdjustedValue_u32_CMockStopIgnore(void)
{
  if(Mock.MyLib_ComputeAdjustedValue_u32_IgnoreBool)
    Mock.MyLib_ComputeAdjustedValue_u32_CallInstance = CMock_Guts_MemNext(Mock.MyLib_ComputeAdjustedValue_u32_CallInstance);
  Mock.MyLib_ComputeAdjustedValue_u32_IgnoreBool = (char)0;
}

void MyLib_ComputeAdjustedValue_u32_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MyLib_ComputeAdjustedValue_u32_CALL_INSTANCE));
  CMOCK_MyLib_ComputeAdjustedValue_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_ComputeAdjustedValue_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MyLib_ComputeAdjustedValue_u32_CallInstance = CMock_Guts_MemChain(Mock.MyLib_ComputeAdjustedValue_u32_CallInstance, cmock_guts_index);
  Mock.MyLib_ComputeAdjustedValue_u32_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void MyLib_ComputeAdjustedValue_u32_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t base_u32, const uint16_t* delta_pc_u16, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MyLib_ComputeAdjustedValue_u32_CALL_INSTANCE));
  CMOCK_MyLib_ComputeAdjustedValue_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_ComputeAdjustedValue_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MyLib_ComputeAdjustedValue_u32_CallInstance = CMock_Guts_MemChain(Mock.MyLib_ComputeAdjustedValue_u32_CallInstance, cmock_guts_index);
  Mock.MyLib_ComputeAdjustedValue_u32_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_MyLib_ComputeAdjustedValue_u32(cmock_call_instance, base_u32, delta_pc_u16, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void MyLib_ComputeAdjustedValue_u32_AddCallback(CMOCK_MyLib_ComputeAdjustedValue_u32_CALLBACK Callback)
{
  Mock.MyLib_ComputeAdjustedValue_u32_IgnoreBool = (char)0;
  Mock.MyLib_ComputeAdjustedValue_u32_CallbackBool = (char)1;
  Mock.MyLib_ComputeAdjustedValue_u32_CallbackFunctionPointer = Callback;
}

void MyLib_ComputeAdjustedValue_u32_Stub(CMOCK_MyLib_ComputeAdjustedValue_u32_CALLBACK Callback)
{
  Mock.MyLib_ComputeAdjustedValue_u32_IgnoreBool = (char)0;
  Mock.MyLib_ComputeAdjustedValue_u32_CallbackBool = (char)0;
  Mock.MyLib_ComputeAdjustedValue_u32_CallbackFunctionPointer = Callback;
}

void MyLib_ComputeAdjustedValue_u32_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t base_u32, const uint16_t* delta_pc_u16, int delta_pc_u16_Depth, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MyLib_ComputeAdjustedValue_u32_CALL_INSTANCE));
  CMOCK_MyLib_ComputeAdjustedValue_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_ComputeAdjustedValue_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MyLib_ComputeAdjustedValue_u32_CallInstance = CMock_Guts_MemChain(Mock.MyLib_ComputeAdjustedValue_u32_CallInstance, cmock_guts_index);
  Mock.MyLib_ComputeAdjustedValue_u32_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_MyLib_ComputeAdjustedValue_u32(cmock_call_instance, base_u32, delta_pc_u16, delta_pc_u16_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void MyLib_ComputeAdjustedValue_u32_CMockIgnoreArg_base_u32(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MyLib_ComputeAdjustedValue_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_ComputeAdjustedValue_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.MyLib_ComputeAdjustedValue_u32_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_base_u32 = 1;
}

void MyLib_ComputeAdjustedValue_u32_CMockIgnoreArg_delta_pc_u16(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MyLib_ComputeAdjustedValue_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_ComputeAdjustedValue_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.MyLib_ComputeAdjustedValue_u32_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_delta_pc_u16 = 1;
}

uint32_t MyLib_AnalyzeArray_u32(uint16_t* values_pu16, size_t len_u32, uint16_t factor_u16)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MyLib_AnalyzeArray_u32_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_MyLib_AnalyzeArray_u32);
  cmock_call_instance = (CMOCK_MyLib_AnalyzeArray_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.MyLib_AnalyzeArray_u32_CallInstance);
  Mock.MyLib_AnalyzeArray_u32_CallInstance = CMock_Guts_MemNext(Mock.MyLib_AnalyzeArray_u32_CallInstance);
  if (Mock.MyLib_AnalyzeArray_u32_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.MyLib_AnalyzeArray_u32_FinalReturn;
    Mock.MyLib_AnalyzeArray_u32_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.MyLib_AnalyzeArray_u32_CallbackBool &&
      Mock.MyLib_AnalyzeArray_u32_CallbackFunctionPointer != NULL)
  {
    uint32_t cmock_cb_ret = Mock.MyLib_AnalyzeArray_u32_CallbackFunctionPointer(values_pu16, len_u32, factor_u16, Mock.MyLib_AnalyzeArray_u32_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_values_pu16)
  {
    UNITY_SET_DETAILS(CMockString_MyLib_AnalyzeArray_u32,CMockString_values_pu16);
    if (cmock_call_instance->Expected_values_pu16 == NULL)
      { UNITY_TEST_ASSERT_NULL(values_pu16, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX16_ARRAY(cmock_call_instance->Expected_values_pu16, values_pu16, cmock_call_instance->Expected_values_pu16_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_len_u32)
  {
    UNITY_SET_DETAILS(CMockString_MyLib_AnalyzeArray_u32,CMockString_len_u32);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_len_u32), (void*)(&len_u32), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_factor_u16)
  {
    UNITY_SET_DETAILS(CMockString_MyLib_AnalyzeArray_u32,CMockString_factor_u16);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_factor_u16, factor_u16, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.MyLib_AnalyzeArray_u32_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.MyLib_AnalyzeArray_u32_CallbackFunctionPointer(values_pu16, len_u32, factor_u16, Mock.MyLib_AnalyzeArray_u32_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_values_pu16_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(values_pu16, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)values_pu16, (const void*)cmock_call_instance->ReturnThruPtr_values_pu16_Val,
      cmock_call_instance->ReturnThruPtr_values_pu16_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_MyLib_AnalyzeArray_u32(CMOCK_MyLib_AnalyzeArray_u32_CALL_INSTANCE* cmock_call_instance, uint16_t* values_pu16, int values_pu16_Depth, size_t len_u32, uint16_t factor_u16);
void CMockExpectParameters_MyLib_AnalyzeArray_u32(CMOCK_MyLib_AnalyzeArray_u32_CALL_INSTANCE* cmock_call_instance, uint16_t* values_pu16, int values_pu16_Depth, size_t len_u32, uint16_t factor_u16)
{
  cmock_call_instance->Expected_values_pu16 = values_pu16;
  cmock_call_instance->Expected_values_pu16_Depth = values_pu16_Depth;
  cmock_call_instance->IgnoreArg_values_pu16 = 0;
  cmock_call_instance->ReturnThruPtr_values_pu16_Used = 0;
  memcpy((void*)(&cmock_call_instance->Expected_len_u32), (void*)(&len_u32),
         sizeof(size_t[sizeof(len_u32) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_len_u32 = 0;
  cmock_call_instance->Expected_factor_u16 = factor_u16;
  cmock_call_instance->IgnoreArg_factor_u16 = 0;
}

void MyLib_AnalyzeArray_u32_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MyLib_AnalyzeArray_u32_CALL_INSTANCE));
  CMOCK_MyLib_AnalyzeArray_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_AnalyzeArray_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MyLib_AnalyzeArray_u32_CallInstance = CMock_Guts_MemChain(Mock.MyLib_AnalyzeArray_u32_CallInstance, cmock_guts_index);
  Mock.MyLib_AnalyzeArray_u32_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.MyLib_AnalyzeArray_u32_IgnoreBool = (char)1;
}

void MyLib_AnalyzeArray_u32_CMockStopIgnore(void)
{
  if(Mock.MyLib_AnalyzeArray_u32_IgnoreBool)
    Mock.MyLib_AnalyzeArray_u32_CallInstance = CMock_Guts_MemNext(Mock.MyLib_AnalyzeArray_u32_CallInstance);
  Mock.MyLib_AnalyzeArray_u32_IgnoreBool = (char)0;
}

void MyLib_AnalyzeArray_u32_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MyLib_AnalyzeArray_u32_CALL_INSTANCE));
  CMOCK_MyLib_AnalyzeArray_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_AnalyzeArray_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MyLib_AnalyzeArray_u32_CallInstance = CMock_Guts_MemChain(Mock.MyLib_AnalyzeArray_u32_CallInstance, cmock_guts_index);
  Mock.MyLib_AnalyzeArray_u32_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void MyLib_AnalyzeArray_u32_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t* values_pu16, size_t len_u32, uint16_t factor_u16, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MyLib_AnalyzeArray_u32_CALL_INSTANCE));
  CMOCK_MyLib_AnalyzeArray_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_AnalyzeArray_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MyLib_AnalyzeArray_u32_CallInstance = CMock_Guts_MemChain(Mock.MyLib_AnalyzeArray_u32_CallInstance, cmock_guts_index);
  Mock.MyLib_AnalyzeArray_u32_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_MyLib_AnalyzeArray_u32(cmock_call_instance, values_pu16, len_u32, len_u32, factor_u16);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void MyLib_AnalyzeArray_u32_AddCallback(CMOCK_MyLib_AnalyzeArray_u32_CALLBACK Callback)
{
  Mock.MyLib_AnalyzeArray_u32_IgnoreBool = (char)0;
  Mock.MyLib_AnalyzeArray_u32_CallbackBool = (char)1;
  Mock.MyLib_AnalyzeArray_u32_CallbackFunctionPointer = Callback;
}

void MyLib_AnalyzeArray_u32_Stub(CMOCK_MyLib_AnalyzeArray_u32_CALLBACK Callback)
{
  Mock.MyLib_AnalyzeArray_u32_IgnoreBool = (char)0;
  Mock.MyLib_AnalyzeArray_u32_CallbackBool = (char)0;
  Mock.MyLib_AnalyzeArray_u32_CallbackFunctionPointer = Callback;
}

void MyLib_AnalyzeArray_u32_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t* values_pu16, int values_pu16_Depth, size_t len_u32, uint16_t factor_u16, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MyLib_AnalyzeArray_u32_CALL_INSTANCE));
  CMOCK_MyLib_AnalyzeArray_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_AnalyzeArray_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MyLib_AnalyzeArray_u32_CallInstance = CMock_Guts_MemChain(Mock.MyLib_AnalyzeArray_u32_CallInstance, cmock_guts_index);
  Mock.MyLib_AnalyzeArray_u32_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_MyLib_AnalyzeArray_u32(cmock_call_instance, values_pu16, values_pu16_Depth, len_u32, factor_u16);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void MyLib_AnalyzeArray_u32_CMockReturnMemThruPtr_values_pu16(UNITY_LINE_TYPE cmock_line, uint16_t const* values_pu16, size_t cmock_size)
{
  CMOCK_MyLib_AnalyzeArray_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_AnalyzeArray_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.MyLib_AnalyzeArray_u32_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_values_pu16_Used = 1;
  cmock_call_instance->ReturnThruPtr_values_pu16_Val = values_pu16;
  cmock_call_instance->ReturnThruPtr_values_pu16_Size = cmock_size;
}

void MyLib_AnalyzeArray_u32_CMockIgnoreArg_values_pu16(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MyLib_AnalyzeArray_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_AnalyzeArray_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.MyLib_AnalyzeArray_u32_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_values_pu16 = 1;
}

void MyLib_AnalyzeArray_u32_CMockIgnoreArg_len_u32(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MyLib_AnalyzeArray_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_AnalyzeArray_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.MyLib_AnalyzeArray_u32_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_len_u32 = 1;
}

void MyLib_AnalyzeArray_u32_CMockIgnoreArg_factor_u16(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MyLib_AnalyzeArray_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_AnalyzeArray_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.MyLib_AnalyzeArray_u32_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_factor_u16 = 1;
}

void MyLib_UpdateGlobalRecord(MyLib_record_t* dest_p, const MyLib_record_t* src_pc)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MyLib_UpdateGlobalRecord_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_MyLib_UpdateGlobalRecord);
  cmock_call_instance = (CMOCK_MyLib_UpdateGlobalRecord_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.MyLib_UpdateGlobalRecord_CallInstance);
  Mock.MyLib_UpdateGlobalRecord_CallInstance = CMock_Guts_MemNext(Mock.MyLib_UpdateGlobalRecord_CallInstance);
  if (Mock.MyLib_UpdateGlobalRecord_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.MyLib_UpdateGlobalRecord_CallbackBool &&
      Mock.MyLib_UpdateGlobalRecord_CallbackFunctionPointer != NULL)
  {
    Mock.MyLib_UpdateGlobalRecord_CallbackFunctionPointer(dest_p, src_pc, Mock.MyLib_UpdateGlobalRecord_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_dest_p)
  {
    UNITY_SET_DETAILS(CMockString_MyLib_UpdateGlobalRecord,CMockString_dest_p);
    if (cmock_call_instance->Expected_dest_p == NULL)
      { UNITY_TEST_ASSERT_NULL(dest_p, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_dest_p), (void*)(dest_p), sizeof(MyLib_record_t), cmock_call_instance->Expected_dest_p_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_src_pc)
  {
    UNITY_SET_DETAILS(CMockString_MyLib_UpdateGlobalRecord,CMockString_src_pc);
    if (cmock_call_instance->Expected_src_pc == NULL)
      { UNITY_TEST_ASSERT_NULL(src_pc, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_src_pc), (void*)(src_pc), sizeof(const MyLib_record_t), cmock_call_instance->Expected_src_pc_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.MyLib_UpdateGlobalRecord_CallbackFunctionPointer != NULL)
  {
    Mock.MyLib_UpdateGlobalRecord_CallbackFunctionPointer(dest_p, src_pc, Mock.MyLib_UpdateGlobalRecord_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_dest_p_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(dest_p, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)dest_p, (const void*)cmock_call_instance->ReturnThruPtr_dest_p_Val,
      cmock_call_instance->ReturnThruPtr_dest_p_Size);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_MyLib_UpdateGlobalRecord(CMOCK_MyLib_UpdateGlobalRecord_CALL_INSTANCE* cmock_call_instance, MyLib_record_t* dest_p, int dest_p_Depth, const MyLib_record_t* src_pc, int src_pc_Depth);
void CMockExpectParameters_MyLib_UpdateGlobalRecord(CMOCK_MyLib_UpdateGlobalRecord_CALL_INSTANCE* cmock_call_instance, MyLib_record_t* dest_p, int dest_p_Depth, const MyLib_record_t* src_pc, int src_pc_Depth)
{
  cmock_call_instance->Expected_dest_p = dest_p;
  cmock_call_instance->Expected_dest_p_Depth = dest_p_Depth;
  cmock_call_instance->IgnoreArg_dest_p = 0;
  cmock_call_instance->ReturnThruPtr_dest_p_Used = 0;
  cmock_call_instance->Expected_src_pc = src_pc;
  cmock_call_instance->Expected_src_pc_Depth = src_pc_Depth;
  cmock_call_instance->IgnoreArg_src_pc = 0;
}

void MyLib_UpdateGlobalRecord_CMockIgnore(void)
{
  Mock.MyLib_UpdateGlobalRecord_IgnoreBool = (char)1;
}

void MyLib_UpdateGlobalRecord_CMockStopIgnore(void)
{
  Mock.MyLib_UpdateGlobalRecord_IgnoreBool = (char)0;
}

void MyLib_UpdateGlobalRecord_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MyLib_UpdateGlobalRecord_CALL_INSTANCE));
  CMOCK_MyLib_UpdateGlobalRecord_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_UpdateGlobalRecord_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MyLib_UpdateGlobalRecord_CallInstance = CMock_Guts_MemChain(Mock.MyLib_UpdateGlobalRecord_CallInstance, cmock_guts_index);
  Mock.MyLib_UpdateGlobalRecord_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void MyLib_UpdateGlobalRecord_CMockExpect(UNITY_LINE_TYPE cmock_line, MyLib_record_t* dest_p, const MyLib_record_t* src_pc)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MyLib_UpdateGlobalRecord_CALL_INSTANCE));
  CMOCK_MyLib_UpdateGlobalRecord_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_UpdateGlobalRecord_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MyLib_UpdateGlobalRecord_CallInstance = CMock_Guts_MemChain(Mock.MyLib_UpdateGlobalRecord_CallInstance, cmock_guts_index);
  Mock.MyLib_UpdateGlobalRecord_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_MyLib_UpdateGlobalRecord(cmock_call_instance, dest_p, 1, src_pc, 1);
}

void MyLib_UpdateGlobalRecord_AddCallback(CMOCK_MyLib_UpdateGlobalRecord_CALLBACK Callback)
{
  Mock.MyLib_UpdateGlobalRecord_IgnoreBool = (char)0;
  Mock.MyLib_UpdateGlobalRecord_CallbackBool = (char)1;
  Mock.MyLib_UpdateGlobalRecord_CallbackFunctionPointer = Callback;
}

void MyLib_UpdateGlobalRecord_Stub(CMOCK_MyLib_UpdateGlobalRecord_CALLBACK Callback)
{
  Mock.MyLib_UpdateGlobalRecord_IgnoreBool = (char)0;
  Mock.MyLib_UpdateGlobalRecord_CallbackBool = (char)0;
  Mock.MyLib_UpdateGlobalRecord_CallbackFunctionPointer = Callback;
}

void MyLib_UpdateGlobalRecord_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, MyLib_record_t* dest_p, int dest_p_Depth, const MyLib_record_t* src_pc, int src_pc_Depth)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MyLib_UpdateGlobalRecord_CALL_INSTANCE));
  CMOCK_MyLib_UpdateGlobalRecord_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_UpdateGlobalRecord_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MyLib_UpdateGlobalRecord_CallInstance = CMock_Guts_MemChain(Mock.MyLib_UpdateGlobalRecord_CallInstance, cmock_guts_index);
  Mock.MyLib_UpdateGlobalRecord_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_MyLib_UpdateGlobalRecord(cmock_call_instance, dest_p, dest_p_Depth, src_pc, src_pc_Depth);
}

void MyLib_UpdateGlobalRecord_CMockReturnMemThruPtr_dest_p(UNITY_LINE_TYPE cmock_line, MyLib_record_t const* dest_p, size_t cmock_size)
{
  CMOCK_MyLib_UpdateGlobalRecord_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_UpdateGlobalRecord_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.MyLib_UpdateGlobalRecord_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_dest_p_Used = 1;
  cmock_call_instance->ReturnThruPtr_dest_p_Val = dest_p;
  cmock_call_instance->ReturnThruPtr_dest_p_Size = cmock_size;
}

void MyLib_UpdateGlobalRecord_CMockIgnoreArg_dest_p(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MyLib_UpdateGlobalRecord_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_UpdateGlobalRecord_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.MyLib_UpdateGlobalRecord_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_dest_p = 1;
}

void MyLib_UpdateGlobalRecord_CMockIgnoreArg_src_pc(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MyLib_UpdateGlobalRecord_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_UpdateGlobalRecord_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.MyLib_UpdateGlobalRecord_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_src_pc = 1;
}

uint32_t MyLib_Orchestrate_u32(uint32_t start_u32, const uint16_t* delta_pc_u16)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MyLib_Orchestrate_u32_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_MyLib_Orchestrate_u32);
  cmock_call_instance = (CMOCK_MyLib_Orchestrate_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.MyLib_Orchestrate_u32_CallInstance);
  Mock.MyLib_Orchestrate_u32_CallInstance = CMock_Guts_MemNext(Mock.MyLib_Orchestrate_u32_CallInstance);
  if (Mock.MyLib_Orchestrate_u32_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.MyLib_Orchestrate_u32_FinalReturn;
    Mock.MyLib_Orchestrate_u32_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.MyLib_Orchestrate_u32_CallbackBool &&
      Mock.MyLib_Orchestrate_u32_CallbackFunctionPointer != NULL)
  {
    uint32_t cmock_cb_ret = Mock.MyLib_Orchestrate_u32_CallbackFunctionPointer(start_u32, delta_pc_u16, Mock.MyLib_Orchestrate_u32_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_start_u32)
  {
    UNITY_SET_DETAILS(CMockString_MyLib_Orchestrate_u32,CMockString_start_u32);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_start_u32, start_u32, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_delta_pc_u16)
  {
    UNITY_SET_DETAILS(CMockString_MyLib_Orchestrate_u32,CMockString_delta_pc_u16);
    if (cmock_call_instance->Expected_delta_pc_u16 == NULL)
      { UNITY_TEST_ASSERT_NULL(delta_pc_u16, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX16_ARRAY(cmock_call_instance->Expected_delta_pc_u16, delta_pc_u16, cmock_call_instance->Expected_delta_pc_u16_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.MyLib_Orchestrate_u32_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.MyLib_Orchestrate_u32_CallbackFunctionPointer(start_u32, delta_pc_u16, Mock.MyLib_Orchestrate_u32_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_MyLib_Orchestrate_u32(CMOCK_MyLib_Orchestrate_u32_CALL_INSTANCE* cmock_call_instance, uint32_t start_u32, const uint16_t* delta_pc_u16, int delta_pc_u16_Depth);
void CMockExpectParameters_MyLib_Orchestrate_u32(CMOCK_MyLib_Orchestrate_u32_CALL_INSTANCE* cmock_call_instance, uint32_t start_u32, const uint16_t* delta_pc_u16, int delta_pc_u16_Depth)
{
  cmock_call_instance->Expected_start_u32 = start_u32;
  cmock_call_instance->IgnoreArg_start_u32 = 0;
  cmock_call_instance->Expected_delta_pc_u16 = delta_pc_u16;
  cmock_call_instance->Expected_delta_pc_u16_Depth = delta_pc_u16_Depth;
  cmock_call_instance->IgnoreArg_delta_pc_u16 = 0;
}

void MyLib_Orchestrate_u32_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MyLib_Orchestrate_u32_CALL_INSTANCE));
  CMOCK_MyLib_Orchestrate_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_Orchestrate_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MyLib_Orchestrate_u32_CallInstance = CMock_Guts_MemChain(Mock.MyLib_Orchestrate_u32_CallInstance, cmock_guts_index);
  Mock.MyLib_Orchestrate_u32_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.MyLib_Orchestrate_u32_IgnoreBool = (char)1;
}

void MyLib_Orchestrate_u32_CMockStopIgnore(void)
{
  if(Mock.MyLib_Orchestrate_u32_IgnoreBool)
    Mock.MyLib_Orchestrate_u32_CallInstance = CMock_Guts_MemNext(Mock.MyLib_Orchestrate_u32_CallInstance);
  Mock.MyLib_Orchestrate_u32_IgnoreBool = (char)0;
}

void MyLib_Orchestrate_u32_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MyLib_Orchestrate_u32_CALL_INSTANCE));
  CMOCK_MyLib_Orchestrate_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_Orchestrate_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MyLib_Orchestrate_u32_CallInstance = CMock_Guts_MemChain(Mock.MyLib_Orchestrate_u32_CallInstance, cmock_guts_index);
  Mock.MyLib_Orchestrate_u32_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void MyLib_Orchestrate_u32_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t start_u32, const uint16_t* delta_pc_u16, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MyLib_Orchestrate_u32_CALL_INSTANCE));
  CMOCK_MyLib_Orchestrate_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_Orchestrate_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MyLib_Orchestrate_u32_CallInstance = CMock_Guts_MemChain(Mock.MyLib_Orchestrate_u32_CallInstance, cmock_guts_index);
  Mock.MyLib_Orchestrate_u32_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_MyLib_Orchestrate_u32(cmock_call_instance, start_u32, delta_pc_u16, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void MyLib_Orchestrate_u32_AddCallback(CMOCK_MyLib_Orchestrate_u32_CALLBACK Callback)
{
  Mock.MyLib_Orchestrate_u32_IgnoreBool = (char)0;
  Mock.MyLib_Orchestrate_u32_CallbackBool = (char)1;
  Mock.MyLib_Orchestrate_u32_CallbackFunctionPointer = Callback;
}

void MyLib_Orchestrate_u32_Stub(CMOCK_MyLib_Orchestrate_u32_CALLBACK Callback)
{
  Mock.MyLib_Orchestrate_u32_IgnoreBool = (char)0;
  Mock.MyLib_Orchestrate_u32_CallbackBool = (char)0;
  Mock.MyLib_Orchestrate_u32_CallbackFunctionPointer = Callback;
}

void MyLib_Orchestrate_u32_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t start_u32, const uint16_t* delta_pc_u16, int delta_pc_u16_Depth, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MyLib_Orchestrate_u32_CALL_INSTANCE));
  CMOCK_MyLib_Orchestrate_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_Orchestrate_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MyLib_Orchestrate_u32_CallInstance = CMock_Guts_MemChain(Mock.MyLib_Orchestrate_u32_CallInstance, cmock_guts_index);
  Mock.MyLib_Orchestrate_u32_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_MyLib_Orchestrate_u32(cmock_call_instance, start_u32, delta_pc_u16, delta_pc_u16_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void MyLib_Orchestrate_u32_CMockIgnoreArg_start_u32(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MyLib_Orchestrate_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_Orchestrate_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.MyLib_Orchestrate_u32_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_start_u32 = 1;
}

void MyLib_Orchestrate_u32_CMockIgnoreArg_delta_pc_u16(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MyLib_Orchestrate_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_Orchestrate_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.MyLib_Orchestrate_u32_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_delta_pc_u16 = 1;
}

uint32_t InternalHelper_u32(uint32_t x_u32, uint16_t y_u16)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_InternalHelper_u32_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_InternalHelper_u32);
  cmock_call_instance = (CMOCK_InternalHelper_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.InternalHelper_u32_CallInstance);
  Mock.InternalHelper_u32_CallInstance = CMock_Guts_MemNext(Mock.InternalHelper_u32_CallInstance);
  if (Mock.InternalHelper_u32_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.InternalHelper_u32_FinalReturn;
    Mock.InternalHelper_u32_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.InternalHelper_u32_CallbackBool &&
      Mock.InternalHelper_u32_CallbackFunctionPointer != NULL)
  {
    uint32_t cmock_cb_ret = Mock.InternalHelper_u32_CallbackFunctionPointer(x_u32, y_u16, Mock.InternalHelper_u32_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_x_u32)
  {
    UNITY_SET_DETAILS(CMockString_InternalHelper_u32,CMockString_x_u32);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_x_u32, x_u32, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_y_u16)
  {
    UNITY_SET_DETAILS(CMockString_InternalHelper_u32,CMockString_y_u16);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_y_u16, y_u16, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.InternalHelper_u32_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.InternalHelper_u32_CallbackFunctionPointer(x_u32, y_u16, Mock.InternalHelper_u32_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_InternalHelper_u32(CMOCK_InternalHelper_u32_CALL_INSTANCE* cmock_call_instance, uint32_t x_u32, uint16_t y_u16);
void CMockExpectParameters_InternalHelper_u32(CMOCK_InternalHelper_u32_CALL_INSTANCE* cmock_call_instance, uint32_t x_u32, uint16_t y_u16)
{
  cmock_call_instance->Expected_x_u32 = x_u32;
  cmock_call_instance->IgnoreArg_x_u32 = 0;
  cmock_call_instance->Expected_y_u16 = y_u16;
  cmock_call_instance->IgnoreArg_y_u16 = 0;
}

void InternalHelper_u32_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_InternalHelper_u32_CALL_INSTANCE));
  CMOCK_InternalHelper_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_InternalHelper_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.InternalHelper_u32_CallInstance = CMock_Guts_MemChain(Mock.InternalHelper_u32_CallInstance, cmock_guts_index);
  Mock.InternalHelper_u32_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.InternalHelper_u32_IgnoreBool = (char)1;
}

void InternalHelper_u32_CMockStopIgnore(void)
{
  if(Mock.InternalHelper_u32_IgnoreBool)
    Mock.InternalHelper_u32_CallInstance = CMock_Guts_MemNext(Mock.InternalHelper_u32_CallInstance);
  Mock.InternalHelper_u32_IgnoreBool = (char)0;
}

void InternalHelper_u32_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_InternalHelper_u32_CALL_INSTANCE));
  CMOCK_InternalHelper_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_InternalHelper_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.InternalHelper_u32_CallInstance = CMock_Guts_MemChain(Mock.InternalHelper_u32_CallInstance, cmock_guts_index);
  Mock.InternalHelper_u32_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void InternalHelper_u32_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t x_u32, uint16_t y_u16, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_InternalHelper_u32_CALL_INSTANCE));
  CMOCK_InternalHelper_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_InternalHelper_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.InternalHelper_u32_CallInstance = CMock_Guts_MemChain(Mock.InternalHelper_u32_CallInstance, cmock_guts_index);
  Mock.InternalHelper_u32_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_InternalHelper_u32(cmock_call_instance, x_u32, y_u16);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void InternalHelper_u32_AddCallback(CMOCK_InternalHelper_u32_CALLBACK Callback)
{
  Mock.InternalHelper_u32_IgnoreBool = (char)0;
  Mock.InternalHelper_u32_CallbackBool = (char)1;
  Mock.InternalHelper_u32_CallbackFunctionPointer = Callback;
}

void InternalHelper_u32_Stub(CMOCK_InternalHelper_u32_CALLBACK Callback)
{
  Mock.InternalHelper_u32_IgnoreBool = (char)0;
  Mock.InternalHelper_u32_CallbackBool = (char)0;
  Mock.InternalHelper_u32_CallbackFunctionPointer = Callback;
}

void InternalHelper_u32_CMockIgnoreArg_x_u32(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_InternalHelper_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_InternalHelper_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.InternalHelper_u32_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_x_u32 = 1;
}

void InternalHelper_u32_CMockIgnoreArg_y_u16(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_InternalHelper_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_InternalHelper_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.InternalHelper_u32_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_y_u16 = 1;
}

uint8_t MyLib_UpdateCounter_u8(uint32_t add_u32)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MyLib_UpdateCounter_u8_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_MyLib_UpdateCounter_u8);
  cmock_call_instance = (CMOCK_MyLib_UpdateCounter_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.MyLib_UpdateCounter_u8_CallInstance);
  Mock.MyLib_UpdateCounter_u8_CallInstance = CMock_Guts_MemNext(Mock.MyLib_UpdateCounter_u8_CallInstance);
  if (Mock.MyLib_UpdateCounter_u8_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.MyLib_UpdateCounter_u8_FinalReturn;
    Mock.MyLib_UpdateCounter_u8_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.MyLib_UpdateCounter_u8_CallbackBool &&
      Mock.MyLib_UpdateCounter_u8_CallbackFunctionPointer != NULL)
  {
    uint8_t cmock_cb_ret = Mock.MyLib_UpdateCounter_u8_CallbackFunctionPointer(add_u32, Mock.MyLib_UpdateCounter_u8_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_add_u32)
  {
    UNITY_SET_DETAILS(CMockString_MyLib_UpdateCounter_u8,CMockString_add_u32);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_add_u32, add_u32, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.MyLib_UpdateCounter_u8_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.MyLib_UpdateCounter_u8_CallbackFunctionPointer(add_u32, Mock.MyLib_UpdateCounter_u8_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_MyLib_UpdateCounter_u8(CMOCK_MyLib_UpdateCounter_u8_CALL_INSTANCE* cmock_call_instance, uint32_t add_u32);
void CMockExpectParameters_MyLib_UpdateCounter_u8(CMOCK_MyLib_UpdateCounter_u8_CALL_INSTANCE* cmock_call_instance, uint32_t add_u32)
{
  cmock_call_instance->Expected_add_u32 = add_u32;
  cmock_call_instance->IgnoreArg_add_u32 = 0;
}

void MyLib_UpdateCounter_u8_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MyLib_UpdateCounter_u8_CALL_INSTANCE));
  CMOCK_MyLib_UpdateCounter_u8_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_UpdateCounter_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MyLib_UpdateCounter_u8_CallInstance = CMock_Guts_MemChain(Mock.MyLib_UpdateCounter_u8_CallInstance, cmock_guts_index);
  Mock.MyLib_UpdateCounter_u8_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.MyLib_UpdateCounter_u8_IgnoreBool = (char)1;
}

void MyLib_UpdateCounter_u8_CMockStopIgnore(void)
{
  if(Mock.MyLib_UpdateCounter_u8_IgnoreBool)
    Mock.MyLib_UpdateCounter_u8_CallInstance = CMock_Guts_MemNext(Mock.MyLib_UpdateCounter_u8_CallInstance);
  Mock.MyLib_UpdateCounter_u8_IgnoreBool = (char)0;
}

void MyLib_UpdateCounter_u8_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MyLib_UpdateCounter_u8_CALL_INSTANCE));
  CMOCK_MyLib_UpdateCounter_u8_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_UpdateCounter_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MyLib_UpdateCounter_u8_CallInstance = CMock_Guts_MemChain(Mock.MyLib_UpdateCounter_u8_CallInstance, cmock_guts_index);
  Mock.MyLib_UpdateCounter_u8_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void MyLib_UpdateCounter_u8_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t add_u32, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MyLib_UpdateCounter_u8_CALL_INSTANCE));
  CMOCK_MyLib_UpdateCounter_u8_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_UpdateCounter_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MyLib_UpdateCounter_u8_CallInstance = CMock_Guts_MemChain(Mock.MyLib_UpdateCounter_u8_CallInstance, cmock_guts_index);
  Mock.MyLib_UpdateCounter_u8_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_MyLib_UpdateCounter_u8(cmock_call_instance, add_u32);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void MyLib_UpdateCounter_u8_AddCallback(CMOCK_MyLib_UpdateCounter_u8_CALLBACK Callback)
{
  Mock.MyLib_UpdateCounter_u8_IgnoreBool = (char)0;
  Mock.MyLib_UpdateCounter_u8_CallbackBool = (char)1;
  Mock.MyLib_UpdateCounter_u8_CallbackFunctionPointer = Callback;
}

void MyLib_UpdateCounter_u8_Stub(CMOCK_MyLib_UpdateCounter_u8_CALLBACK Callback)
{
  Mock.MyLib_UpdateCounter_u8_IgnoreBool = (char)0;
  Mock.MyLib_UpdateCounter_u8_CallbackBool = (char)0;
  Mock.MyLib_UpdateCounter_u8_CallbackFunctionPointer = Callback;
}

void MyLib_UpdateCounter_u8_CMockIgnoreArg_add_u32(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MyLib_UpdateCounter_u8_CALL_INSTANCE* cmock_call_instance = (CMOCK_MyLib_UpdateCounter_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.MyLib_UpdateCounter_u8_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_add_u32 = 1;
}

