/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include "MyLib_Orchestrate_u32.h"
#include "unity.h"
#include "mock_MyLib.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_MyLib_Orchestrate_u32_WhenDeltaIsNullAndStartIsZero_ReturnsExpectedValue(void);
extern void test_MyLib_Orchestrate_u32_WhenDeltaIsNotNullAndStartIsNonZero_UsesCorrectDelta(void);
extern void test_MyLib_Orchestrate_u32_RecordIdIsLower16BitsOfBase_Verified(void);
extern void test_MyLib_Orchestrate_u32_RecordValueIsHalfOfBase_Verified(void);
extern void test_MyLib_Orchestrate_u32_CallsInternalHelperWithCorrectArguments_Verified(void);
extern void test_MyLib_Orchestrate_u32_CallsProcessRecordWithMultiplierValue_Verified(void);
extern void test_MyLib_Orchestrate_u32_ReturnIsBaseAddCounter_Verified(void);
extern void test_MyLib_Orchestrate_u32_ReturnWithLargeValues_WraparoundHandled(void);
extern void test_MyLib_Orchestrate_u32_WhenStartIsMaxUint32_HandledCorrectly(void);
extern void test_MyLib_Orchestrate_u32_WhenCounterIsZero_ReturnsBaseValue(void);
extern void test_MyLib_Orchestrate_u32_WhenMultipleDeltaValues_AllProcessedCorrectly(void);
extern void test_MyLib_Orchestrate_u32_GlobalCounterPreservedAcrossCalls_Verified(void);
extern void test_MyLib_Orchestrate_u32_SequentialCalls_CounterAccumulatesAsExpected(void);
extern void test_MyLib_Orchestrate_u32_WithIgnoredArguments_FunctionStillExecutes(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
  mock_MyLib_Init();
}
static void CMock_Verify(void)
{
  mock_MyLib_Verify();
}
static void CMock_Destroy(void)
{
  mock_MyLib_Destroy();
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_MyLib_Orchestrate_u32.c");
  run_test(test_MyLib_Orchestrate_u32_WhenDeltaIsNullAndStartIsZero_ReturnsExpectedValue, "test_MyLib_Orchestrate_u32_WhenDeltaIsNullAndStartIsZero_ReturnsExpectedValue", 49);
  run_test(test_MyLib_Orchestrate_u32_WhenDeltaIsNotNullAndStartIsNonZero_UsesCorrectDelta, "test_MyLib_Orchestrate_u32_WhenDeltaIsNotNullAndStartIsNonZero_UsesCorrectDelta", 83);
  run_test(test_MyLib_Orchestrate_u32_RecordIdIsLower16BitsOfBase_Verified, "test_MyLib_Orchestrate_u32_RecordIdIsLower16BitsOfBase_Verified", 118);
  run_test(test_MyLib_Orchestrate_u32_RecordValueIsHalfOfBase_Verified, "test_MyLib_Orchestrate_u32_RecordValueIsHalfOfBase_Verified", 149);
  run_test(test_MyLib_Orchestrate_u32_CallsInternalHelperWithCorrectArguments_Verified, "test_MyLib_Orchestrate_u32_CallsInternalHelperWithCorrectArguments_Verified", 178);
  run_test(test_MyLib_Orchestrate_u32_CallsProcessRecordWithMultiplierValue_Verified, "test_MyLib_Orchestrate_u32_CallsProcessRecordWithMultiplierValue_Verified", 204);
  run_test(test_MyLib_Orchestrate_u32_ReturnIsBaseAddCounter_Verified, "test_MyLib_Orchestrate_u32_ReturnIsBaseAddCounter_Verified", 233);
  run_test(test_MyLib_Orchestrate_u32_ReturnWithLargeValues_WraparoundHandled, "test_MyLib_Orchestrate_u32_ReturnWithLargeValues_WraparoundHandled", 261);
  run_test(test_MyLib_Orchestrate_u32_WhenStartIsMaxUint32_HandledCorrectly, "test_MyLib_Orchestrate_u32_WhenStartIsMaxUint32_HandledCorrectly", 292);
  run_test(test_MyLib_Orchestrate_u32_WhenCounterIsZero_ReturnsBaseValue, "test_MyLib_Orchestrate_u32_WhenCounterIsZero_ReturnsBaseValue", 318);
  run_test(test_MyLib_Orchestrate_u32_WhenMultipleDeltaValues_AllProcessedCorrectly, "test_MyLib_Orchestrate_u32_WhenMultipleDeltaValues_AllProcessedCorrectly", 343);
  run_test(test_MyLib_Orchestrate_u32_GlobalCounterPreservedAcrossCalls_Verified, "test_MyLib_Orchestrate_u32_GlobalCounterPreservedAcrossCalls_Verified", 379);
  run_test(test_MyLib_Orchestrate_u32_SequentialCalls_CounterAccumulatesAsExpected, "test_MyLib_Orchestrate_u32_SequentialCalls_CounterAccumulatesAsExpected", 406);
  run_test(test_MyLib_Orchestrate_u32_WithIgnoredArguments_FunctionStillExecutes, "test_MyLib_Orchestrate_u32_WithIgnoredArguments_FunctionStillExecutes", 436);

  CMock_Guts_MemFreeFinal();
  return UNITY_END();
}
