/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include "MyLib.h"
#include "MyLib_UpdateCounter_u8.h"
#include "unity.h"
#include "mock_MyLib.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_system_not_ready_returns_error_code_1_and_no_counter_update(void);
extern void test_system_ready_saturation_disabled_zero_increment_returns_0_counter_unchanged(void);
extern void test_system_ready_saturation_disabled_small_increment_returns_0_counter_updated(void);
extern void test_system_ready_saturation_disabled_increment_causing_wraparound_returns_0_counter_wraps(void);
extern void test_system_ready_saturation_enabled_increment_below_limit_returns_0_counter_updated(void);
extern void test_system_ready_saturation_enabled_increment_exactly_at_limit_returns_0_counter_equals_limit(void);
extern void test_system_ready_saturation_enabled_increment_exceeding_limit_by_one_returns_2_counter_clamped(void);
extern void test_system_ready_saturation_enabled_large_increment_far_exceeding_limit_returns_2_counter_clamped(void);
extern void test_system_ready_saturation_enabled_increment_causing_wraparound_before_saturation_returns_2_counter_clamped(void);
extern void test_cycle_counter_toggle_saturation_toggles_after_16_calls(void);
extern void test_cycle_counter_toggle_saturation_does_not_toggle_on_call_15(void);
extern void test_cycle_counter_toggle_saturation_does_not_toggle_on_call_17(void);
extern void test_cycle_counter_toggle_persistence_saturation_toggles_again_at_call_32(void);
extern void test_system_not_ready_after_multiple_ready_calls_returns_1_counter_unchanged(void);
extern void test_saturation_boundary_counter_at_limit_minus_one_increment_by_one_returns_0_counter_equals_limit(void);
extern void test_saturation_boundary_counter_at_limit_increment_by_one_returns_2_counter_remains_at_limit(void);
extern void test_saturation_boundary_counter_at_zero_increment_to_exactly_limit_returns_0_counter_equals_limit(void);
extern void test_saturation_boundary_counter_at_zero_increment_to_limit_plus_one_returns_2_counter_clamped(void);
extern void test_maximum_uint32_increment_counter_at_zero_add_max_saturation_disabled_returns_0_counter_wraps_to_max(void);
extern void test_maximum_uint32_increment_counter_at_one_add_max_saturation_disabled_returns_0_counter_wraps_to_zero(void);
extern void test_saturation_disabled_counter_at_max_increment_by_one_returns_0_counter_wraps_to_zero(void);
extern void test_limit_set_to_max_saturation_enabled_any_increment_returns_0_new_value_cannot_exceed_limit(void);
extern void test_limit_set_to_zero_saturation_enabled_any_nonzero_increment_returns_2_counter_clamped_to_zero(void);
extern void test_cycle_counter_increments_across_system_not_ready_calls(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
  mock_MyLib_Init();
}
static void CMock_Verify(void)
{
  mock_MyLib_Verify();
}
static void CMock_Destroy(void)
{
  mock_MyLib_Destroy();
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_maximum_uint32_increment_counter_at_zero_add_max_saturation_disabled_returns_0_counter_wraps_to_max.c");
  run_test(test_system_not_ready_returns_error_code_1_and_no_counter_update, "test_system_not_ready_returns_error_code_1_and_no_counter_update", 10);
  run_test(test_system_ready_saturation_disabled_zero_increment_returns_0_counter_unchanged, "test_system_ready_saturation_disabled_zero_increment_returns_0_counter_unchanged", 24);
  run_test(test_system_ready_saturation_disabled_small_increment_returns_0_counter_updated, "test_system_ready_saturation_disabled_small_increment_returns_0_counter_updated", 39);
  run_test(test_system_ready_saturation_disabled_increment_causing_wraparound_returns_0_counter_wraps, "test_system_ready_saturation_disabled_increment_causing_wraparound_returns_0_counter_wraps", 54);
  run_test(test_system_ready_saturation_enabled_increment_below_limit_returns_0_counter_updated, "test_system_ready_saturation_enabled_increment_below_limit_returns_0_counter_updated", 68);
  run_test(test_system_ready_saturation_enabled_increment_exactly_at_limit_returns_0_counter_equals_limit, "test_system_ready_saturation_enabled_increment_exactly_at_limit_returns_0_counter_equals_limit", 83);
  run_test(test_system_ready_saturation_enabled_increment_exceeding_limit_by_one_returns_2_counter_clamped, "test_system_ready_saturation_enabled_increment_exceeding_limit_by_one_returns_2_counter_clamped", 98);
  run_test(test_system_ready_saturation_enabled_large_increment_far_exceeding_limit_returns_2_counter_clamped, "test_system_ready_saturation_enabled_large_increment_far_exceeding_limit_returns_2_counter_clamped", 113);
  run_test(test_system_ready_saturation_enabled_increment_causing_wraparound_before_saturation_returns_2_counter_clamped, "test_system_ready_saturation_enabled_increment_causing_wraparound_before_saturation_returns_2_counter_clamped", 128);
  run_test(test_cycle_counter_toggle_saturation_toggles_after_16_calls, "test_cycle_counter_toggle_saturation_toggles_after_16_calls", 143);
  run_test(test_cycle_counter_toggle_saturation_does_not_toggle_on_call_15, "test_cycle_counter_toggle_saturation_does_not_toggle_on_call_15", 165);
  run_test(test_cycle_counter_toggle_saturation_does_not_toggle_on_call_17, "test_cycle_counter_toggle_saturation_does_not_toggle_on_call_17", 183);
  run_test(test_cycle_counter_toggle_persistence_saturation_toggles_again_at_call_32, "test_cycle_counter_toggle_persistence_saturation_toggles_again_at_call_32", 203);
  run_test(test_system_not_ready_after_multiple_ready_calls_returns_1_counter_unchanged, "test_system_not_ready_after_multiple_ready_calls_returns_1_counter_unchanged", 228);
  run_test(test_saturation_boundary_counter_at_limit_minus_one_increment_by_one_returns_0_counter_equals_limit, "test_saturation_boundary_counter_at_limit_minus_one_increment_by_one_returns_0_counter_equals_limit", 250);
  run_test(test_saturation_boundary_counter_at_limit_increment_by_one_returns_2_counter_remains_at_limit, "test_saturation_boundary_counter_at_limit_increment_by_one_returns_2_counter_remains_at_limit", 265);
  run_test(test_saturation_boundary_counter_at_zero_increment_to_exactly_limit_returns_0_counter_equals_limit, "test_saturation_boundary_counter_at_zero_increment_to_exactly_limit_returns_0_counter_equals_limit", 280);
  run_test(test_saturation_boundary_counter_at_zero_increment_to_limit_plus_one_returns_2_counter_clamped, "test_saturation_boundary_counter_at_zero_increment_to_limit_plus_one_returns_2_counter_clamped", 295);
  run_test(test_maximum_uint32_increment_counter_at_zero_add_max_saturation_disabled_returns_0_counter_wraps_to_max, "test_maximum_uint32_increment_counter_at_zero_add_max_saturation_disabled_returns_0_counter_wraps_to_max", 310);
  run_test(test_maximum_uint32_increment_counter_at_one_add_max_saturation_disabled_returns_0_counter_wraps_to_zero, "test_maximum_uint32_increment_counter_at_one_add_max_saturation_disabled_returns_0_counter_wraps_to_zero", 324);
  run_test(test_saturation_disabled_counter_at_max_increment_by_one_returns_0_counter_wraps_to_zero, "test_saturation_disabled_counter_at_max_increment_by_one_returns_0_counter_wraps_to_zero", 338);
  run_test(test_limit_set_to_max_saturation_enabled_any_increment_returns_0_new_value_cannot_exceed_limit, "test_limit_set_to_max_saturation_enabled_any_increment_returns_0_new_value_cannot_exceed_limit", 352);
  run_test(test_limit_set_to_zero_saturation_enabled_any_nonzero_increment_returns_2_counter_clamped_to_zero, "test_limit_set_to_zero_saturation_enabled_any_nonzero_increment_returns_2_counter_clamped_to_zero", 367);
  run_test(test_cycle_counter_increments_across_system_not_ready_calls, "test_cycle_counter_increments_across_system_not_ready_calls", 382);

  CMock_Guts_MemFreeFinal();
  return UNITY_END();
}
