/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include "MyLib_UpdateCounter_u8.h"
#include "unity.h"
#include "mock_MyLib.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_MyLib_UpdateCounter_u8_SystemNotReady_ReturnOne(void);
extern void test_MyLib_UpdateCounter_u8_SystemNotReady_CounterPreserved(void);
extern void test_MyLib_UpdateCounter_u8_SystemReady_NormalAdd_ReturnZero(void);
extern void test_MyLib_UpdateCounter_u8_SaturationEnabled_OverflowPrevented(void);
extern void test_MyLib_UpdateCounter_u8_SaturationDisabled_OverflowAllowed(void);
extern void test_MyLib_UpdateCounter_u8_ZeroAddition(void);
extern void test_MyLib_UpdateCounter_u8_MaxValueAddition_SaturationEnabled(void);
extern void test_MyLib_UpdateCounter_u8_CounterAtLimit_SaturationTriggered(void);
extern void test_MyLib_UpdateCounter_u8_CounterAtLimit_NoAddition(void);
extern void test_MyLib_UpdateCounter_u8_CycleCountTogglePattern_Every16Calls(void);
extern void test_MyLib_UpdateCounter_u8_CycleCountToggle_FindPattern(void);
extern void test_MyLib_UpdateCounter_u8_MultipleCycleToggles(void);
extern void test_MyLib_UpdateCounter_u8_CycleToggle_FromDisabledToEnabled(void);
extern void test_MyLib_UpdateCounter_u8_CustomLimit_BelowLimit(void);
extern void test_MyLib_UpdateCounter_u8_CustomLimit_ExceedsLimit(void);
extern void test_MyLib_UpdateCounter_u8_CounterAtZero_WithAddition(void);
extern void test_MyLib_UpdateCounter_u8_ExactLimitBoundary_NoOverflow(void);
extern void test_MyLib_UpdateCounter_u8_PastLimitBoundary_OverflowBy1(void);
extern void test_MyLib_UpdateCounter_u8_SaturationDisabled_ExactBoundary(void);
extern void test_MyLib_UpdateCounter_u8_SystemReadyTransition(void);
extern void test_MyLib_UpdateCounter_u8_LargeCounterValue_WithinLimit(void);
extern void test_MyLib_UpdateCounter_u8_LargeCounterValue_ExceedsLimit(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
  mock_MyLib_Init();
}
static void CMock_Verify(void)
{
  mock_MyLib_Verify();
}
static void CMock_Destroy(void)
{
  mock_MyLib_Destroy();
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_MyLib_UpdateCounter_u8.c");
  run_test(test_MyLib_UpdateCounter_u8_SystemNotReady_ReturnOne, "test_MyLib_UpdateCounter_u8_SystemNotReady_ReturnOne", 30);
  run_test(test_MyLib_UpdateCounter_u8_SystemNotReady_CounterPreserved, "test_MyLib_UpdateCounter_u8_SystemNotReady_CounterPreserved", 53);
  run_test(test_MyLib_UpdateCounter_u8_SystemReady_NormalAdd_ReturnZero, "test_MyLib_UpdateCounter_u8_SystemReady_NormalAdd_ReturnZero", 77);
  run_test(test_MyLib_UpdateCounter_u8_SaturationEnabled_OverflowPrevented, "test_MyLib_UpdateCounter_u8_SaturationEnabled_OverflowPrevented", 102);
  run_test(test_MyLib_UpdateCounter_u8_SaturationDisabled_OverflowAllowed, "test_MyLib_UpdateCounter_u8_SaturationDisabled_OverflowAllowed", 127);
  run_test(test_MyLib_UpdateCounter_u8_ZeroAddition, "test_MyLib_UpdateCounter_u8_ZeroAddition", 152);
  run_test(test_MyLib_UpdateCounter_u8_MaxValueAddition_SaturationEnabled, "test_MyLib_UpdateCounter_u8_MaxValueAddition_SaturationEnabled", 176);
  run_test(test_MyLib_UpdateCounter_u8_CounterAtLimit_SaturationTriggered, "test_MyLib_UpdateCounter_u8_CounterAtLimit_SaturationTriggered", 201);
  run_test(test_MyLib_UpdateCounter_u8_CounterAtLimit_NoAddition, "test_MyLib_UpdateCounter_u8_CounterAtLimit_NoAddition", 226);
  run_test(test_MyLib_UpdateCounter_u8_CycleCountTogglePattern_Every16Calls, "test_MyLib_UpdateCounter_u8_CycleCountTogglePattern_Every16Calls", 253);
  run_test(test_MyLib_UpdateCounter_u8_CycleCountToggle_FindPattern, "test_MyLib_UpdateCounter_u8_CycleCountToggle_FindPattern", 294);
  run_test(test_MyLib_UpdateCounter_u8_MultipleCycleToggles, "test_MyLib_UpdateCounter_u8_MultipleCycleToggles", 349);
  run_test(test_MyLib_UpdateCounter_u8_CycleToggle_FromDisabledToEnabled, "test_MyLib_UpdateCounter_u8_CycleToggle_FromDisabledToEnabled", 388);
  run_test(test_MyLib_UpdateCounter_u8_CustomLimit_BelowLimit, "test_MyLib_UpdateCounter_u8_CustomLimit_BelowLimit", 418);
  run_test(test_MyLib_UpdateCounter_u8_CustomLimit_ExceedsLimit, "test_MyLib_UpdateCounter_u8_CustomLimit_ExceedsLimit", 443);
  run_test(test_MyLib_UpdateCounter_u8_CounterAtZero_WithAddition, "test_MyLib_UpdateCounter_u8_CounterAtZero_WithAddition", 468);
  run_test(test_MyLib_UpdateCounter_u8_ExactLimitBoundary_NoOverflow, "test_MyLib_UpdateCounter_u8_ExactLimitBoundary_NoOverflow", 492);
  run_test(test_MyLib_UpdateCounter_u8_PastLimitBoundary_OverflowBy1, "test_MyLib_UpdateCounter_u8_PastLimitBoundary_OverflowBy1", 517);
  run_test(test_MyLib_UpdateCounter_u8_SaturationDisabled_ExactBoundary, "test_MyLib_UpdateCounter_u8_SaturationDisabled_ExactBoundary", 542);
  run_test(test_MyLib_UpdateCounter_u8_SystemReadyTransition, "test_MyLib_UpdateCounter_u8_SystemReadyTransition", 567);
  run_test(test_MyLib_UpdateCounter_u8_LargeCounterValue_WithinLimit, "test_MyLib_UpdateCounter_u8_LargeCounterValue_WithinLimit", 597);
  run_test(test_MyLib_UpdateCounter_u8_LargeCounterValue_ExceedsLimit, "test_MyLib_UpdateCounter_u8_LargeCounterValue_ExceedsLimit", 622);

  CMock_Guts_MemFreeFinal();
  return UNITY_END();
}
