/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include "MyLib_AnalyzeArray_u32.h"
#include "unity.h"
#include "mock_MyLib.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_AnalyzeArray_u32_NULL_pointer_returns_zero(void);
extern void test_AnalyzeArray_u32_zero_length_returns_zero(void);
extern void test_AnalyzeArray_u32_single_element_factor_1(void);
extern void test_AnalyzeArray_u32_single_element_factor_zero(void);
extern void test_AnalyzeArray_u32_single_element_factor_max(void);
extern void test_AnalyzeArray_u32_multiple_elements_factor_2(void);
extern void test_AnalyzeArray_u32_multiple_elements_factor_zero(void);
extern void test_AnalyzeArray_u32_in_place_modification(void);
extern void test_AnalyzeArray_u32_sum_accumulation_10_elements(void);
extern void test_AnalyzeArray_u32_large_array_factor_5(void);
extern void test_AnalyzeArray_u32_mock_function_called_correct_params(void);
extern void test_AnalyzeArray_u32_mock_return_value_unused(void);
extern void test_AnalyzeArray_u32_all_zeros_with_factor(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
  mock_MyLib_Init();
}
static void CMock_Verify(void)
{
  mock_MyLib_Verify();
}
static void CMock_Destroy(void)
{
  mock_MyLib_Destroy();
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_MyLib_AnalyzeArray_u32.c");
  run_test(test_AnalyzeArray_u32_NULL_pointer_returns_zero, "test_AnalyzeArray_u32_NULL_pointer_returns_zero", 50);
  run_test(test_AnalyzeArray_u32_zero_length_returns_zero, "test_AnalyzeArray_u32_zero_length_returns_zero", 73);
  run_test(test_AnalyzeArray_u32_single_element_factor_1, "test_AnalyzeArray_u32_single_element_factor_1", 97);
  run_test(test_AnalyzeArray_u32_single_element_factor_zero, "test_AnalyzeArray_u32_single_element_factor_zero", 118);
  run_test(test_AnalyzeArray_u32_single_element_factor_max, "test_AnalyzeArray_u32_single_element_factor_max", 138);
  run_test(test_AnalyzeArray_u32_multiple_elements_factor_2, "test_AnalyzeArray_u32_multiple_elements_factor_2", 158);
  run_test(test_AnalyzeArray_u32_multiple_elements_factor_zero, "test_AnalyzeArray_u32_multiple_elements_factor_zero", 180);
  run_test(test_AnalyzeArray_u32_in_place_modification, "test_AnalyzeArray_u32_in_place_modification", 202);
  run_test(test_AnalyzeArray_u32_sum_accumulation_10_elements, "test_AnalyzeArray_u32_sum_accumulation_10_elements", 227);
  run_test(test_AnalyzeArray_u32_large_array_factor_5, "test_AnalyzeArray_u32_large_array_factor_5", 248);
  run_test(test_AnalyzeArray_u32_mock_function_called_correct_params, "test_AnalyzeArray_u32_mock_function_called_correct_params", 270);
  run_test(test_AnalyzeArray_u32_mock_return_value_unused, "test_AnalyzeArray_u32_mock_return_value_unused", 291);
  run_test(test_AnalyzeArray_u32_all_zeros_with_factor, "test_AnalyzeArray_u32_all_zeros_with_factor", 310);

  CMock_Guts_MemFreeFinal();
  return UNITY_END();
}
